### ISSUE TITLE
Upgrading from 0.55 to latest, can't get past 404 Not Found on git.fetch

### ISSUE THREAD

**Issue by gimre** [isomorphic-git/isomorphic-git#1103]
I am using:
- Node version
- no bundler, installed from npm directly (v 1.3.1)

I'm a upgrading a previous script I had that was checking out a private github repo and doing some modification before pushing back to remote.

Am currently stuck at
```
HttpError: HTTP Error: 404 Not Found
    at Function.discover (node_modules/isomorphic-git/index.cjs:6309:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async _fetch (node_modules/isomorphic-git/index.cjs:6934:22)
    at async Object.fetch (node_modules/isomorphic-git/index.cjs:8686:12)
    at async index.js:97:3 {
  caller: 'git.fetch',
  name: 'HttpError',
  code: 'HttpError',
  data: { statusCode: 404, statusMessage: 'Not Found' }
}
```

I noticed in the docs authentication was changed from passing a `token` to passing an `onAuth` handler so tried to add that but it is not getting called and still getting the 404.

https://isomorphic-git.org/docs/en/onAuth

Reverting code and version back to 0.55 confirms that everything works as before.

Any ideas what I'm doing wrong?

Thanks,
Gabriel

**Comment by rayman1104** [comment]
@gimre do you use [Personal access tokens](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line)? If yes, check next `onAuth` handler:
```ts
const onAuth = () => ({
  username: process.env.GIT_USER,
  password: process.env.GIT_TOKEN,
});
```

Also, double-check that url of the repo has `.git` in the end - the url in the docs doesn't have it and it cost me several hours of debugging. So, the url should look like this:
```ts
const url = 'https://github.com/org/repo.git';
await git.clone({ fs, http, dir, onAuth, url });
```

**Comment by wmhilton** [comment]
> the url in the docs doesn't have it and it cost me several hours of debugging.

I feel your pain! I absolutely hate how GitHub it does this. I've spent hours figuring out it's weird behavior - it depends on your User-Agent header ([see `headers` docs](https://isomorphic-git.org/docs/en/headers#user-agent-header)):

> Regretably, some git hosting services have User-Agent specific behavior. For instance, GitHub will correctly interpret git HTTP requests made to a repository URL that is missing the `.git` suffix but _ONLY_ if the User-Agent starts with `git/`. And in fact, does not interpret git HTTP requests for _gists_ correctly _at all_ unless the User-Agent start with `git/` (bug [#259](https://github.com/isomorphic-git/isomorphic-git/issues/259)).
