### ISSUE TITLE
`readCommit` returns `NotFoundError: Could not find ` instead of commit

### ISSUE THREAD

**Issue by crutchcorn** [isomorphic-git/isomorphic-git#1159]
Please be sure to mention:
- whether you are using Node or the Browser
- how you are using it (if you are using a bundler what bundler; if you are using a `<script>` tag what CDN URL)

I am building on React Native and am trying to do a `readCommit` immediately after a `log`. I am doing the following logic:

```javascript
const commits = await git.log({
    fs,
    dir: repo.path,
    ref: repo.currentBranchName,
  });

git
      .readCommit({gitdir: repo.path, fs: fs, oid: commits[0].oid})
      .then(ccommit => console.log(ccommit))
```

And yet, despite `commits` being filly filled, I get an error like the following:

```
NotFoundError: Could not find 25050456bb4ecd1e509118aefadcd2b0c5a1092f.
    at _callee26$ (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:187373:27)
    at tryCatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25445:19)
    at Generator.invoke [as _invoke] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25621:24)
    at Generator.prototype.<computed> [as next] (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:25488:23)
    at f (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:187276:25)
    at a (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:187293:17)
    at tryCallOne (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:26804:14)
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:26905:17
    at http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30470:21
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:30359:9)
```

For a more thorough code sample, you can follow the following application logic that outlines how I do the `git.log`:

https://github.com/crutchcorn/GitShark/blob/wip-commit-details-info/src/views/repository-history/repository-history.tsx#L16
https://github.com/crutchcorn/GitShark/blob/wip-commit-details-info/src/store/gitLogSlice.ts#L21
https://github.com/crutchcorn/GitShark/blob/wip-commit-details-info/src/services/git/gitLog.ts#L13

And then how I do the `readCommit`:

https://github.com/crutchcorn/GitShark/blob/wip-commit-details-info/src/views/repository-history/repository-history.tsx#L23
https://github.com/crutchcorn/GitShark/blob/wip-commit-details-info/src/views/commit-details/commit-details.tsx#L22

**Comment by crutchcorn** [comment]
I just confirmed with `node` usage as well, just to make sure it wasn't a one-off with my React Native config:

```
const git = require('isomorphic-git');
const fs = require('fs');
const http = require('isomorphic-git/http/web');
const fetch = require('node-fetch');
globalThis.fetch = fetch;

const  path =  'batteries-not-included';

await git.clone({fs, dir: 'batteries-not-included', url: 'https://github.com/unicorn-utterances/batteries-not-included.git', http, singleBranch: true})

console.log(await git.log({fs, dir: path, ref: 'integration'})); // which shows a commit with an oid of  '90ca297ae63acafcb9e4c1a52a3911b36e4a7841'

git.readCommit({fs, gitdir: path, oid: '90ca297ae63acafcb9e4c1a52a3911b36e4a7841'}).then(console.log).catch(console.error)
```

Which gives the error:

```
> NotFoundError: Could not find 90ca297ae63acafcb9e4c1a52a3911b36e4a7841.
    at _readObject (C:\Users\crutchcorn\git\GitGui\test\node_modules\isomorphic-git\index.cjs:2811:11)
    at async resolveCommit (C:\Users\crutchcorn\git\GitGui\test\node_modules\isomorphic-git\index.cjs:9647:28)
    at async _readCommit (C:\Users\crutchcorn\git\GitGui\test\node_modules\isomorphic-git\index.cjs:9673:38)
    at async Object.readCommit (C:\Users\crutchcorn\git\GitGui\test\node_modules\isomorphic-git\index.cjs:10862:12) {
  caller: 'git.readCommit',
  name: 'NotFoundError',
  code: 'NotFoundError',
  data: { what: '90ca297ae63acafcb9e4c1a52a3911b36e4a7841' }
}
```

**Comment by crutchcorn** [comment]
I'm an idiot. I should have been using `dir` instead of `gitdir`. The highlighting on the documentation confused me at first:

https://isomorphic-git.org/docs/en/readCommit
