### ISSUE TITLE
Allow reading of staged / index blob content in walk (GitWalkerIndex)

### ISSUE THREAD

**Issue by s0** [isomorphic-git/isomorphic-git#1165]
In the following lines, it is suggested that it's not possible to get the contents of a staged file: https://github.com/isomorphic-git/isomorphic-git/blob/63f3a9c7b96bca5ae68f5a553dee9d7c12cc8928/src/models/GitWalkerIndex.js#L96-L98

It's also mentioned ([in the documentation](https://isomorphic-git.org/docs/en/walk#walkerentry-content)):

> "STAGE walkers always return undefined since the file contents are never stored in the stage."

However as far as I am aware, staged files do have their content stored and readily accessible in git, as is demonstrated by the command `git ls-files -s <filepath>`, which will return the object sha of the blob contents for the given path (along with mode etc...).

For the time being, to work around this limitation, i've had to run `git ls-files -s` in a child process to retreive this sha, and then call `readBlob()` separately on the resulting output from the child process.

I''d love for isomorphic-git to be able to do this :)

**Comment by Kysumi** [comment]
```
  return await git.walk({
    fs,
    dir: gitDir,
    trees: [git.STAGE()],
    map: async (filePath, [A]) => console.log(A),
  });
```

This seems to work for me. Is this what you were looking for?

**Comment by s0** [comment]
> ```
>   return await git.walk({
>     fs,
>     dir: gitDir,
>     trees: [git.STAGE()],
>     map: async (filePath, [A]) => console.log(A),
>   });
> ```
> 
> This seems to work for me. Is this what you were looking for?

Not quite, specifically calling [`A.content()`](https://isomorphic-git.org/docs/en/walk#walkerentry-content) is what fails.

**Comment by Kysumi** [comment]
Oh right, I ended up doing the following. It seems to accomplish what I'm after

```JS
const readContentsFromHash = async (hash, gitDir, filePath = null) => {
  let config = {
    fs,
    dir: gitDir,
    oid: hash,
  };

  if (filePath) {
    config = {
      ...config,
      filepath: filePath,
    };
  }

  const { blob } = await git.readBlob(config);

  return new TextDecoder().decode(blob);
};

const getStagedFileContents = async (gitDir, stagedFilePaths) => {
  const map = async (filePath, [A]) => {
    if (stagedFilePaths.includes(filePath)) {
      const contents = await readContentsFromHash(await A.oid(), gitDir);

      return {
        filePath: `/${filePath}`,
        contents,
      };
    }
  };

  return await git.walk({
    fs,
    dir: gitDir,
    trees: [git.STAGE()],
    map,
  });
};
```

**Comment by jcubic** [comment]
@s0 does this solve your issue? I can add this to documentation, it seems that there is a place for snippets of code.

**Comment by eugeniol** [comment]
> ```js
>  filePath: `/${filePath}`,
> ```

This does not work for me, looks like the oid() is not found under STAGE at all.

```
readObject.js:51 Uncaught (in promise) NotFoundError: Could not find 1d49f19656159feeee334c800da5fa8fd10007a4.
    at readObject.js:51:11
    at Generator.next (<anonymous>)
    at f (InternalError.js:16:22)
    at a2 (InternalError.js:16:22)
```

**Comment by jcubic** [comment]
@eugeniol can you show your exact code?
