### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by willstott101** [isomorphic-git/isomorphic-git#1224]
Using node 14 (I believe because of the `"type": "module"` in `package.json`) the CLI doesn't work.

The CLI uses `require` which is not available in an ESM context.

```
wstott@wstott-1804:/tmp$ mktemp -d tmpnode-XXXXXXXX
wstott@wstott-1804:/tmp$ cd tmpnode-YNkwT6GT/
wstott@wstott-1804:/tmp/tmpnode-YNkwT6GT$ ls
wstott@wstott-1804:/tmp/tmpnode-YNkwT6GT$ node --version
v14.8.0
wstott@wstott-1804:/tmp/tmpnode-YNkwT6GT$ npm init
wstott@wstott-1804:/tmp/tmpnode-YNkwT6GT$ npm i isomorphic-git
wstott@wstott-1804:/tmp/tmpnode-YNkwT6GT$ npx isogit
file:///tmp/tmpnode-YNkwT6GT/node_modules/isomorphic-git/cli.js:2
const fs = require('fs')
           ^

ReferenceError: require is not defined
    at file:///tmp/tmpnode-YNkwT6GT/node_modules/isomorphic-git/cli.js:2:12
    at ModuleJob.run (internal/modules/esm/module_job.js:140:23)
    at async Loader.import (internal/modules/esm/loader.js:165:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

If I edit the `package.json` in `node_modules` to not include `"type": "module",` then the CLI starts working.

**Comment by willstott101** [comment]
Thanks!
