### ISSUE TITLE
Too much pending tasks error on git statusMatrix

### ISSUE THREAD

**Issue by coderaiser** [isomorphic-git/isomorphic-git#1277]
Please be sure to mention:
- `Node`
- `require`

```js
/home/coderaiser/putout/node_modules/async-lock/lib/index.js:149
		done(false, new Error('Too much pending tasks'));
		            ^

Error: Too much pending tasks
    at AsyncLock.acquire (/home/coderaiser/putout/node_modules/async-lock/lib/index.js:149:15)
    at Function.acquire (/home/coderaiser/putout/node_modules/isomorphic-git/index.cjs:854:16)
    at GitWalkerFs.oid (/home/coderaiser/putout/node_modules/isomorphic-git/index.cjs:3945:29)
    at WorkdirEntry.oid (/home/coderaiser/putout/node_modules/isomorphic-git/index.cjs:3870:23)
    at map (/home/coderaiser/putout/node_modules/isomorphic-git/index.cjs:12991:38)
    at async walk (/home/coderaiser/putout/node_modules/isomorphic-git/index.cjs:5430:20)
    at async Promise.all (index 2)
    at async walk (/home/coderaiser/putout/node_modules/isomorphic-git/index.cjs:5432:28)
    at async Promise.all (index 0)
    at async walk (/home/coderaiser/putout/node_modules/isomorphic-git/index.cjs:5432:28) {
  caller: 'git.statusMatrix'
}
```

It's related to [async-lock v1.2.5](https://github.com/rogierschouten/async-lock/blob/master/History.md#125) and [maxPending option](https://github.com/rogierschouten/async-lock/issues/39).

**Comment by coderaiser** [comment]
Fixed in [async-lock v1.2.6](https://github.com/rogierschouten/async-lock/blob/master/History.md#126).
