### ISSUE TITLE
Is the type of ` WalkerMap` wrong?

### ISSUE THREAD

**Issue by mkizka** [isomorphic-git/isomorphic-git#1313]
Now `type WalkerMap` is 
```ts
export type WalkerMap = (filename: string, entries: WalkerEntry[] | null) => Promise<any>;
```
https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/api/walk.js#L9-L14

https://github.com/isomorphic-git/isomorphic-git/blob/26f761e540709da7920db1288469cb9ed5be5c1c/src/typedefs.js#L91-L100

But the item of `entries` can be `null`.
Is correct `(WalkerEntry | null)[]`? ~~If so, I want to create a Pull Request.~~ Created #1314
https://github.com/isomorphic-git/isomorphic-git/blob/89c0da78d5ebf3c9f2754b3c8d557155dd70c8d7/__tests__/test-walk.js#L155-L172

**Comment by mkizka** [comment]
git diff snippets faild

https://isomorphic-git.org/docs/en/snippets#git-diff-name-status-commithash1-commithash2
```console
(node:1954) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'type' of null
    at map (/home/ubuntu/workspace/isomorphic-git-issue/walker.js:15:20)
    at walk (/home/ubuntu/workspace/isomorphic-git-issue/node_modules/isomorphic-git/index.cjs:5432:26)
```

```js
const fs = require("fs");
const git = require("isomorphic-git");
const http = require("isomorphic-git/http/node");

async function getFileStateChanges(commitHash1, commitHash2, dir) {
  return git.walk({
    fs,
    dir,
    trees: [git.TREE({ ref: commitHash1 }), git.TREE({ ref: commitHash2 })],
    map: async function (filepath, [A, B]) {
      // ignore directories
      if (filepath === ".") {
        return;
      }
      if ((await A.type()) === "tree" || (await B.type()) === "tree") {
        return;
      }

      // generate ids
      const Aoid = await A.oid();
      const Boid = await B.oid();

      // determine modification type
      let type = "equal";
      if (Aoid !== Boid) {
        type = "modify";
      }
      if (Aoid === undefined) {
        type = "add";
      }
      if (Boid === undefined) {
        type = "remove";
      }
      if (Aoid === undefined && Boid === undefined) {
        console.log("Something weird happened:");
        console.log(A);
        console.log(B);
      }

      return {
        path: `/${filepath}`,
        type: type,
      };
    },
  });
}

async function main() {
  const url = "https://github.com/isomorphic-git/isomorphic-git";
  const dir = `./${url.split("/").pop()}`;
  if (!fs.existsSync(dir)) {
    await git.clone({ fs, http, dir, url: `${url}.git` });
  }
  const result = await getFileStateChanges("v1.7.1", "v1.7.2", dir);
  console.log(result);
}

main();
```

**Comment by pixelfrog** [comment]
I've also been running into issues with WalkerMap attempting to implement the git diff code snippet.  Would like to see this PR merged in soon so I can take advantage of this fix!
