### ISSUE TITLE
Pushing local directory to newly created Gitlab repo got 422 error

### ISSUE THREAD

**Issue by biki0109** [isomorphic-git/isomorphic-git#1374]
Hi, I'm currently trying to push my local directory to an empty `Gitlab` repo using the git actions as follow: init -> addRemote -> add -> commit -> push. All of this is using Node

## Expected result
The flow should work normally

## Current behaviour
Got 422 error `Unprocessable entity` on the push step.
This is the full error log
```bash
HttpError: HTTP Error: 422 Unprocessable Entity
    at Function.connect (/Users/my-name/Desktop/test/node_modules/isomorphic-git/index.cjs:6617:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async _push (/Users/my-name/Desktop/test/node_modules/isomorphic-git/index.cjs:11310:15)
    at async push (/Users/my-name/Desktop/test/node_modules/isomorphic-git/index.cjs:11431:12)
    at async no (/Users/my-name/Desktop/test/index.js:48:5) {
  caller: 'git.push',
  code: 'HttpError',
  data: {
    statusCode: 422,
    statusMessage: 'Unprocessable Entity',
    response: undefined
  }
}
```

## Step to reproduce
- Create a blank project on Gitlab (not initialized with README.md)
- Use the sample code below
```javascript
const globby = require("globby");
const { push, init, add, addRemote, commit } = require("isomorphic-git");
const http = require('isomorphic-git/http/node')
const fs = require('fs-extra')

const execute = async () => {
    // init
    await init({fs, dir: './push'})
    // add remote
    await addRemote({
        fs,
        dir: './push',
        remote: 'origin',
        url: 'https://gitlab.com/<my-name>/empty',
        force: true,
    })

    // add files
    const paths = await globby(['./**', './**/.*', '!.git'], {
        cwd: './push',
        gitignore: true,
        dot: true,
    });

    for (const filepath of paths) {
        console.log(filepath)
        await add({ fs, dir: './push', filepath: filepath });
    }

    // commit
    let committ = await commit({
        fs,
        dir: './push',
        message: 'initial commit',
        author: { name: 'my.name', email: 'my.email' },
        committer: { name: 'my.name', email: 'my.email' },
    });

    // push
    await push({
        fs,
        http,
        dir: './push',
        remote: 'origin',
        ref: 'master',
        force: true,
        onAuth: () => ({ 
            username: 'oauth2',
            password: password, // this is my private gitlab token with full access
        }),
    }).catch(e => {
        console.log(e)
    })
}

execute()
```

## Environment
- MacOS Catalina 10.15.7
- Node version: 12.22.1

**Comment by biki0109** [comment]
This issue was caused by invalid access scope, the commit's email and username were not a member of the organization.

**Comment by jcubic** [comment]
I think we can still improve the error message, something like suffix "please make sure that you have rights to the repo" or put it into FAQ.

**Comment by mojavelinux** [comment]
FYI, I just hit this today. It seems like, occasionally, GitLab sends something back that isomorphic-git doesn't like. When I ran it again a few minutes later, it worked fine. So it definitely seems like a GitLab issue...but of course looks pretty confusing on our end.
