### ISSUE TITLE
Some times we get a TypeError: Cannot read property 'length' of undefined 

### ISSUE THREAD

**Issue by indigo423** [isomorphic-git/isomorphic-git#1399]
We are using isomorphic-git in Antora 2.3.4 where its package.json tells us: `"isomorphic-git": "0.78.5"` the error message we are seeing is shown as the following:

```
#!/bin/sh -eo pipefail
npm i -g antora-site-generator-lunr
DOCSEARCH_ENABLED=true DOCSEARCH_ENGINE=lunr NODE_PATH="$(npm -g root)" antora --generator antora-site-generator-lunr --stacktrace generate antora-playbook.yml

+ antora-site-generator-lunr@0.6.1
added 254 packages from 210 contributors in 11.703s
Error: Unknown TypeError: See cause (url: https://github.com/OpenNMS/opennms-js.git)
    at transformGitCloneError (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/@antora/content-aggregator/lib/aggregate-content.js:794:22)
    at git.clone.then.then.catch (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/@antora/content-aggregator/lib/aggregate-content.js:184:17)
Caused by: TypeError: Cannot read property 'length' of undefined
    at Inflate.push (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/pako/lib/inflate.js:218:30)
    at listpack (/usr/local/lib/node_modules/antora-site-generator-lunr/node_modules/isomorphic-git/dist/for-node/isomorphic-git/index.js:3230:16)

Exited with code exit status 1

CircleCI received exit code 1
```
We can't really easily reproduce the problem, we just see it as a flapper in our CI/CD pipeline. The feedback we got from the Antora project was hinting to the isomorphic-git client: https://github.com/Mogztter/antora-site-generator-lunr/issues/97#issuecomment-874332413 dealing with timeouts and retries while dealing with repositories hosted on GitHub. If you have any hints for us on how we can mitigate this problem would nice.

Thank you in advance

**Comment by wmhilton** [comment]
Perfect timing. We just started seeing this error at Stoplight as well, so I'm on it lol. Not sure what changed that this started happening now, but I think I see the problem itself.

**Comment by mojavelinux** [comment]
Wow! Thanks @wmhilton! I really appreciate you taking the time to investigate and fix this. You really saved us!

**Comment by jcubic** [comment]
Yes, it was great, and you probably also fixed the build script since I've seen few emails with iso-git-bot that were missing in other merged PR.

I need to say that I would not have a clue what to do with this issue.
