### ISSUE TITLE
Improve error message: Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by linonetwo** [isomorphic-git/isomorphic-git#1433]
Please be sure to mention:
- NodeJS
- how you are using it

```js
// TypeError: Cannot read properties of null (reading 'split')
at new ge (isomorphic-git/index.js:1477:30)
at Function.from (isomorphic-git/index.js:1500:12)
at Function.config [as get] (isomorphic-git/index.js:1616:22)
at gitdir (isomorphic-git/index.js:10167:9)
at Object.remotes [as listRemotes] (isomorphic-git/index.js:10198:31)
```

when try to

```js
import git from 'isomorphic-git';
// ...
const remotes = await git.listRemotes({ fs, dir });
```

**Comment by dherault** [comment]
I'm having this error too, here is my setup:
- NodeJS v18.6.0
- isomorphic-git v1.21.0

![image](https://user-images.githubusercontent.com/4154003/201778189-6cb787fa-016f-4ae9-ac82-670bb9ae832e.png)

My code is:
```ts
await git.commit({
  ...repository,
  message,
})
```

where repository has the `fs`, `dir` and `gitDir` keys.

--> Solution: use `gitdir` not `gitDir` :)

**Comment by linonetwo** [comment]
So what is the difference between `gitdir and dir` here？

**Comment by jcubic** [comment]
gitdir is `./repo/.git` and dir is `./repo` so as you can see you don't need to specify gitdir (unless maybe with bare repos, I'm not sure how they work).

**Comment by mojavelinux** [comment]
That's correct. If you don't specify `gitdir`, then isomorphic git will use the default value of dir + `.git`.

You only need to specify `gitdir` if it's not located directly inside `dir`. Such cases include a bare repository (in which case `dir` is not relevant, only `gitdir`) or a linked worktree, where the `dir` and `gitdir` are separated from each other. So most of the time, you don't need to specify `gitdir`.

> with bare repos, I'm not sure how they work

A bare repository is simply the `.git` folder with no worktree. It's for when you only need to perform operations on the git index and not checked out files.

**Comment by marcelklehr** [comment]
Also getting this semi regularly

**Comment by jcubic** [comment]
@marcelklehr do you want to contribute and make the error better?
