### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by henryhu712** [isomorphic-git/isomorphic-git#1434]
I followed contributing instructions, tried to test just after installed, but got an error:

```
npm install

npm test

> isomorphic-git@0.0.0-development test /Users/henry/isomorphic-git
> nps test

/Users/henry/isomorphic-git/node_modules/nps/dist/bin-utils/index.js:67
    throw err;
    ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/henry/isomorphic-git/package-scripts.js
require() of ES modules is not supported.
require() of /Users/henry/isomorphic-git/package-scripts.js from /Users/henry/isomorphic-git/node_modules/nps/dist/bin-utils/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename package-scripts.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/henry/isomorphic-git/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at requireDefaultFromModule (/Users/henry/isomorphic-git/node_modules/nps/dist/bin-utils/index.js:200:13)
    at attemptModuleRequire (/Users/henry/isomorphic-git/node_modules/nps/dist/bin-utils/index.js:186:14)
    at loadConfig (/Users/henry/isomorphic-git/node_modules/nps/dist/bin-utils/index.js:90:14)
    at getPSConfig (/Users/henry/isomorphic-git/node_modules/nps/dist/bin-utils/parser.js:274:35)
    at parse (/Users/henry/isomorphic-git/node_modules/nps/dist/bin-utils/parser.js:124:18) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by sosuisen** [comment]
The following is my workaround. After that, `npm test` proceeds halfway through. Do you have a solution for the remaining problem?

1. Rename package-script.js to package-script.cjs.
2. Add the following .npsrc for nested nps to recognize the place of package-scripts.cjs. (Resolve https://github.com/sezna/nps/issues/230#issuecomment-872572229)
```
{
  "config": "./package-scripts.cjs"
}
```
3. Rename `__tests__/__helpers__/set-TRAVIS_PULL_REQUEST_SHA.js` to `__tests__/__helpers__/set-TRAVIS_PULL_REQUEST_SHA.cjs`. Rewrite the filename in package-scripts.cjs as well.
4. Rename .prettierrc.js to .prettierrc.cjs.
5. Update prettier to v2.1.0 to enable .prettierrc.cjs as a valid config file.
    (See https://prettier.io/blog/2020/08/24/2.1.0.html#support-cjs-and-json5-configuration-files-8890httpsgithubcomprettierprettierpull8890-8957httpsgithubcomprettierprettierpull8957-by-fiskerhttpsgithubcomfisker )
6. Run `eslint --fix .` and fix the rest of the lint errors manually to align with prettier@2.1.0
7. Rename webpack.config.js to webpack.config.cjs
8. Rename `__tests__/__helpers__/make_http_index.js` to `__tests__/__helpers__/make_http_index.cjs`. Rewrite the filename in package-scripts.cjs as well.
9. Add ignorePatterns in .eslintrc.json because I don't know why, but .eslintignore had no effect.
```
"ignorePatterns": ["/dist/", "*.mjs"],
```
10. Rename `__tests__/__helpers__/generate-docs.js` to `__tests__/__helpers__/generate-docs.cjs`. Rewrite the filename in package-scripts.cjs as well.
11. Rename jest.config.js to jest.config.cjs. Rewrite the filename in package-scripts.cjs as well.
12. Update jest to v25.1.0 to enable jest.config.cjs as a valid config file.
   (See https://github.com/facebook/jest/releases/tag/v25.1.0 )
13. Rename karma.conf.js to karma.conf.cjs. Rewrite the filename in package-scripts.cjs as well.
14. Run `npm test` and get the following results:

![shot_211103_214123](https://user-images.githubusercontent.com/13513812/140070074-1cad667c-b971-4856-a87f-b1e419d986ea.png)

test.jest passed. However, test.karma stops by 'Error in config file!'.

My guess is that the necessary environment variables for test.karma are missing.

You can try the same by applying my pull request, run `eslint --fix .`, fix  the rest of the lint errors manually, and `npm test`.

Can you tell me anything about the test.karma failure?

**Comment by jcubic** [comment]
Sorry, I have no idea what causes the error, I also don't know how to debug this.

**Comment by sosuisen** [comment]
I have solved test.karma failure. Now npm test passes on my local environment.

However, the test does not pass on azure-pipelines, so my PR cannot be accepted.
See the following discussion for details:
https://github.com/isomorphic-git/isomorphic-git/pull/1436

**Comment by seanpoulter** [comment]
@henryhu712, what version of Node.js and npm were you using?
