### ISSUE TITLE
File not found after creating and committing new file

### ISSUE THREAD

**Issue by DePasqualeOrg** [isomorphic-git/isomorphic-git#1558]
I'm running isomorphic-git in Node. I created a repository and ran `git.log` with individual files specified under `filepath`, which worked. Then I created a new file called `test.md` in the repository, committed it, and ran `git.log({ fs, dir, filepath: 'test.md' })`, but now I get the following error:

```
<redacted>/node_modules/.pnpm/isomorphic-git@1.17.1/node_modules/isomorphic-git/index.cjs:4740
  throw new NotFoundError(`file or directory found at "${oid}:${filepath}"`)
        ^

NotFoundError: Could not find file or directory found at "9b332a9ebe2b4937143a6adbaa8e64ae71eb676d:test.md".
    at _resolveFilepath (<redacted>/node_modules/.pnpm/isomorphic-git@1.17.1/node_modules/isomorphic-git/index.cjs:4740:9)
    at resolveFilepath (<redacted>/node_modules/.pnpm/isomorphic-git@1.17.1/node_modules/isomorphic-git/index.cjs:4690:17)
    at async _log (<redacted>/node_modules/.pnpm/isomorphic-git@1.17.1/node_modules/isomorphic-git/index.cjs:10714:20)
    at async Object.log (<redacted>/node_modules/.pnpm/isomorphic-git@1.17.1/node_modules/isomorphic-git/index.cjs:10859:12)
    at async file://<redacted>/test.js:10:16 {
  caller: 'git.log',
  code: 'NotFoundError',
  data: {
    what: 'file or directory found at "9b332a9ebe2b4937143a6adbaa8e64ae71eb676d:test.md"'
  }
}

Node.js v17.9.0
```

This only happens when I run `git.log` with the new file specified. The command works with the previously existing files in the repository. The file exists in the filesystem, and running `git log -p -- test.md` on the command line works. Why can't isomorphic-git find the file?

**Comment by jcubic** [comment]
I can confirm:

```javascript
const git = require('isomorphic-git');
const path = require('path');
const fs = require('fs');
const http = require('isomorphic-git/http/node');

const dir = 'gaiman';

function exists(file) {
  return fs.promises.access(file, fs.constants.F_OK)
           .then(() => true)
           .catch(() => false)
}

(async () => {
    if (await exists(dir)) {
        await fs.promises.mkdir(dir, { recursive: true });
    }
    await git.clone({
        fs,
        http,
        dir,
        url: 'https://github.com/jcubic/gaiman.git'
    });
    const fname = 'test.txt';
    await fs.promises.writeFile(path.join(dir, fname), 'HELLO');
    await git.add({
        fs,
        dir,
        filepath: fname
    });
    await git.commit({
        fs,
        dir,
        author: {
            email: 'jcubic@onet.pl',
            name: 'Jakub T. Jankiewicz'
        },
        message: `add ${fname} file`
    });
    console.log(await git.log({
        fs,
        dir,
        filepath: fname
    }));
})();
```

`git.log` works fine and return proper commit message.

**Comment by araknast** [comment]
Seems like the issue is in the following code in src/commands/log.js
```
if (!found) {
  if (!force && !follow) throw e
  if (isOk && lastFileOid) {
    commits.push(lastCommit)
     // break
  }
}
```
The pull request I've created seems to fix this, but since this is @snowyu 's code I'd like some input from them to make sure I'm not breaking anything.

**Comment by jcubic** [comment]
@araknast the only way to make sure is to create proper unit tests. Right now they are failing because of some disconnect issue, so you may need to re base after the tests are fixed.

**Comment by araknast** [comment]
Hmm, which specific tests are failing? Running `npm test` on my machine seems to go smoothly.
