### ISSUE TITLE
Invalid checksum in GitIndex buffer while running salesforce push command

### ISSUE THREAD

**Issue by meta-love-gupta** [isomorphic-git/isomorphic-git#1721]
I am using salesforce push command to push my local changes using the below command from window command prompt
`sfdx force:source:push -f --json`

And here is the output of command
`c:\M5\ffa>sfdx force:source:push -f --json
{
  "status": 1,
  "name": "Internal",
  "message": "An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709",
  "exitCode": 1,
  "context": "Push",
  "stack": "Internal: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709\n    at Function.wrap (C:\\Users\\Love\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\core\\lib\\sfError.js:84:25)\n    at Push.catch (C:\\Users\\Love\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:283:38)\n    at async Push._run (C:\\Users\\Love\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@salesforce\\command\\lib\\sfdxCommand.js:106:13)\n    at async Config.runCommand (C:\\Users\\Love\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\core\\lib\\config\\config.js:272:25)\n    at async run (C:\\Users\\Love\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\@oclif\\core\\lib\\main.js:74:5)\nCaused by: Internal: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected  but saw da39a3ee5e6b4b0d3255bfef95601890afd80709\n    at Function.fromBuffer (C:\\Users\\Love\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\isomorphic-git\\index.cjs:637:13)\n    at async updateCachedIndexFile (C:\\Users\\Love\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\isomorphic-git\\index.cjs:846:17)\n    at async C:\\Users\\Love\\AppData\\Roaming\\npm\\node_modules\\sfdx-cli\\node_modules\\isomorphic-git\\index.cjs:884:9",
  "warnings": [],
  "commandName": "Push"
}`
![image](https://user-images.githubusercontent.com/79889577/213922904-c494a3f6-f37e-42bf-8649-126f7ae8ac65.png)

**Comment by jcubic** [comment]
Sorry, I don't know Salesforce and I don't have time to debug their system. So if the error came from their service you need to contact Salesforce support, and they need to debug this themself. Unless this is code that you wrote, then the only way to fix this is to debug this yourself.

**Comment by lemanschik** [comment]
looks looks like this is related to wrong type use will fix it in https://github.com/lemanschik/git where i prepare a total rewrite into clean ESNext that is directly load able. + some extra features like JSONP server and httpserver + sharedWorker

**Comment by dead-end** [comment]
The issue at foresales: [https://github.com/forcedotcom/cli/issues/2194](https://github.com/forcedotcom/cli/issues/2194)
