### ISSUE TITLE
Pushing to private GitHub repository fails

### ISSUE THREAD

**Issue by Lotes** [isomorphic-git/isomorphic-git#1722]
Everything works (clone, branch, add, commit)... even the `onAuth`. Until I `push` to my private repo.

```ts
async function push(dir: string, ref: string) {
  await git.push({ fs, http, onAuth, dir, ref, force: true, remote: 'origin', remoteRef: ref });
}

const pat = () => env.GITHUB_PAT;
const owner = "Lotes";
const ref = "lotes/some/branch";
const onAuth: AuthCallback = () => {
  return {
    username: owner,
    password: pat(),
  };
};
```

I get the following errors:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at StreamReader.read (...\node_modules\isomorphic-git\index.cjs:2340:39)
    ...
ParseError: Expected "unpack ok" or "unpack [error message]" but received "".
    at parseReceivePackResponse (...\node_modules\isomorphic-git\index.cjs:11616:11)
```

I tried out with fine-grained and classic PAT. Any ideas what is going wrong?
I am using isomorphic-git version `1.21.0`.

**Comment by jcubic** [comment]
Do you use an access token? Did you add proper permissions? Can you push from canonical git with the same authentication method?

**Comment by Lotes** [comment]
Yes, thanks for replying :)... it is a personal access token (PAT) from GitHub.

I tried two PATs:
1. a fine-grained one, restricted to the private repo and with option "contents" on READ/WRITE access
2. a classic one with the OAuth scopes "user" and "repo"

Both tokens work with `git push https://Lotes:my_pat@github.com/Lotes/private_repo`.

**Comment by jcubic** [comment]
Then I have no idea, this project is contributor driven I'm a maintainer but I rarely write any code myself. I'm also not that familiar with the code base and git internals. I also don't have much time. I mostly do code reviews and merge Pull Requests. I become a maintainer so the project doesn't die because the original author left.

So if you want this to be fixed you will need to debug this yourself. Any contribution and fixes you can make are welcome.

**Comment by Lotes** [comment]
OK, thanks for your time. I think I can debug it, at least I can try.

**Comment by Lotes** [comment]
Here are my findings:
- `git-upload-pack` is fetched by the push command
- the response is passed to  `GitSideBand.demux`
- whose resulting packfile is passed into `parseReceivePackResponse`
- but packfile is empty

**Comment by jcubic** [comment]
And the push was not successful? There are no data on GitHub?
Maybe GitHub support will help. Unless you can figure out what exactly is wrong on your own.

**Comment by Lotes** [comment]
I tried to replace only the push step with canonical git. Git refuses the push because of entry duplication inside of the git folder.

Maybe it helps someone else. I will postpone the usage of isomorph-git FTM. The planned feature on my project was just an optional idea. But I really like your API, compared to other solutions.

**Comment by Lotes** [comment]
I am closing this issue. Whoever faces the same problems, feel free to reopen it, again.

**Comment by konsumer** [comment]
I did some testing with git commandline. If I use my user/token (from an openauth login) it works, so I tried with URL using auth like this:

```
https://username:password@github.com/slimplate/private-tester.git
```

And it did work. It seems like the library is ignoring auth options.

**Comment by konsumer** [comment]
I can either PR the docs to reflect this, or PR the library to use auth options, but the token stuff looks a bit more complicated (and is also ignored) so it might take a bit longer to fix.

**Comment by jcubic** [comment]
I would prefer to update the code to match the docs.

**Comment by konsumer** [comment]
> I would prefer to update the code to match the docs.

From [here](https://isomorphic-git.org/docs/en/authentication) I can commit to fixing `username`/`password` (which will work fine with github, as illustrated above.)

Is `token` param just `password`? I think `oauth2format`, at least for github, is historical (seems to work fine with basic auth.)

I am noticing no headers are sent with any of these options, so I think it wasn't working how it's supposed to, anyway.

**Comment by mojavelinux** [comment]
> I would prefer to update the code to match the docs.

I don't think that's the right choice. The documentation is clearly lagging here. In isomorphic-git 1.x, the auth model was changed to be passed using the onAuth property. See https://isomorphic-git.org/docs/en/push The function no longer accepts username/password options directly. The onAuth is described here: https://isomorphic-git.org/docs/en/onAuth Let's not roll back changes which were intentionally made.

**Comment by konsumer** [comment]
Honestly, I don't really care either way. I have a fix for my usecase (to put the username/token in the URL.) In general, I really don't like it when code doesn't do what the docs say, and in this case it took me a while to figure it out, so I want to help the next person who comes along. 

I'm happy to fix it either way (docs-match-code or code-matches-docs,) but don't personally have a strong opinion about which way to fix that. This is a 10 minute fix, either way. If the username/password options have been removed, `onAuth` is totally fine (although I do think the name is a bit misleading) but [these docs](https://isomorphic-git.org/docs/en/authentication) are just wrong, and should be updated.

**Comment by mojavelinux** [comment]
I'd be fine with showing that the username and password can be added to the URL (though I still think the onAuth/onAuthFailed callbacks should be mentioned). The point I was trying to make is that there are no more username/password options, which was a reply to Jakub. We're in agreement that the page in the docs (which was probably overlooked as it's a secondary page) is showing an option which no longer exists. As long as the page is corrected so that it shows something that does work, I'm fine with that.

**Comment by jcubic** [comment]
Agree user/password is fine to have in the docs but the main API is using user/password

AFAIK auth object is `{username, password: token}` (when using access token) not very intuitive if I may say. This is what I keep using because I have had 2FA for a long time.

**Comment by konsumer** [comment]
@jcubic I think that is part of the problem, though, `username`/`password` params have been removed from push, and are ignored.

**Comment by konsumer** [comment]
For some reason I can't auto-link to this issue, but I made a PR [here](https://github.com/isomorphic-git/isomorphic-git/pull/1728) for the docs. This is a low-priority for me, and I don't have a lot of time/bandwidth for back-and-forth about it. Feel free to ignore it, or add to it however you want.

**Comment by mojavelinux** [comment]
I commented on the PR. Looks good to me. Thanks!

**Comment by jcubic** [comment]
@konsumer I've merged your PR but I would still check why `onAuth` doesn't work. I understand why username and password don't work but not so much about `onAuth`.

**Comment by ninjadev64** [comment]
I'm confused. I'm trying to push with a PAT and am able to do so by supplying the URL with a username and password.

However, using a basic onAuth function `const onAuth = () => ({ username: "ninjadev64", password: "token_here" });` throws a 401...

**Comment by jcubic** [comment]
@ninjadev64 Please share your whole code. It's hard to say if you only shared one function. This is just a tip: if want help from anyone share a self-contained, minimal example that you can test, otherwise no one will be able to help you and you only waste people's time that need to ask for more details.

**Comment by ninjadev64** [comment]
@jcubic
It's as simple as
```js
git.clone({ fs, http, dir, url: "https://github.com/ninjadev64/isomorphic-git-testing", onAuth, corsProxy: "https://cors.isomorphic-git.org" });
```
with onAuth being defined as the function I shared in my previous comment.

**Comment by mojavelinux** [comment]
I'm pretty sure the pattern for using an PAT token on GitHub is:

https://TOKEN:@github.com/org/project-docs

That would mean the username needs to be the token and the password needs to be empty. Otherwise, GitHub thinks you are trying to use a username/password, which won't work.

**Comment by jcubic** [comment]
I've just pushed to [test the repo](https://github.com/jcubic/test-repo) with an older version of isomorphic-git, using username and token as password.

I'm not sure how the new version is different.

**Comment by mojavelinux** [comment]
Hmm, according to https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#using-a-personal-access-token-on-the-command-line it does work in the password field. That seems new, or maybe I'm just not remembering it correctly. I've always put it in the username field with an empty password and I know that works.
