### ISSUE TITLE
Error while running feth with just URL on repo without remotes

### ISSUE THREAD

**Issue by SergeyKalutsky** [isomorphic-git/isomorphic-git#1723]
Hi)
I've got an error:

> /Users/sergeykalutsky/lib/bridge/bridge/node_modules/isomorphic-git/index.cjs:1712
>         throw new NoRefspecError(remote)
>               ^
> NoRefspecError: Could not find a fetch refspec for remote "origin". Make sure the config file has an entry like the following:
> [remote "origin"]
>         fetch = +refs/heads/*:refs/remotes/origin/*
> 
>     at Function.updateRemoteRefs (/Users/sergeykalutsky/lib/bridge/bridge/node_modules/isomorphic-git/index.cjs:1712:15)
>     at async _fetch (/Users/sergeykalutsky/lib/bridge/bridge/node_modules/isomorphic-git/index.cjs:7588:24)
>     at async Object.fetch (/Users/sergeykalutsky/lib/bridge/bridge/node_modules/isomorphic-git/index.cjs:9273:12) {
>   caller: 'git.fetch',
>   code: 'NoRefspecError',
>   data: { remote: 'origin' }

while running fetch
```js
const result = await git.fetch({
        fs,
        http,
        dir: dir,
        ref: 'master',
        url: 'https://github.com/SergeyKalutsky/test2303.git',
        tags: false
    })
```
The repo doesn't have any remotes. It throws an error. Not sure if I do not understand something and it is intended behavior or it is a bug. Thought I would let you know.

**Comment by jcubic** [comment]
How did you clone the repo? How you can have no refs after the clone?

**Comment by SergeyKalutsky** [comment]
I cloned the repo and removed origin, since I wanted to change the main remote. But since all git related operations are done programatically its easier to just use URL. Pushing without origin just by URL is ok. But not fetching. In the docs it states that I need just one.

**Comment by jcubic** [comment]
Ok so the error say what is wrong:

```
NoRefspecError: Could not find a fetch refspec for remote "origin". Make sure the config file has an entry like the following:
[remote "origin"]
fetch = +refs/heads/:refs/remotes/origin/
```

origin is required if you removed the origin you need to add it back.

Note that this project is driven by contributors. There is no main author that will write all the code and fix all the bugs. So if you think that this is an error you will need to fix it yourself. All contributions are welcome.

**Comment by SergeyKalutsky** [comment]
Ok. ill look into into it when I will get free time. I think, that if ref is optional and URL is provided it should not give an error. Thank you.
