### ISSUE TITLE
Buffer not set correcly

### ISSUE THREAD

**Issue by domlen2003** [isomorphic-git/isomorphic-git#1753]
## Setup
Browser, bundled with Vite (SvelteKit)

## Reproduce
Create try a (browser based) git clone as per docs using ESM import syntax.

## Behaviour
The following error occurs:
```error
ReferenceError: Buffer is not defined
    at StreamReader._next (index.js:2450:7)
    at async StreamReader._init (index.js:2493:19)
    at async StreamReader.read (index.js:2420:24)
    at async read (index.js:6754:22)
    at async parseRefsAdResponse (index.js:6805:17)
    at async GitRemoteHTTP.discover (index.js:6996:26)
    at async _fetch (index.js:7640:22)
    at async _clone (index.js:8017:42)
    at async Object.clone (index.js:8140:12)
```

## Hot-Fix
This problem is fixed when adding the following lines:

```typescript
import {Buffer} from "buffer";

self.Buffer = Buffer;
```

## Real-Fix
Investigate why Buffer is not defined/not imported properly when using the described setup.

**Comment by jcubic** [comment]
I think that the problem is with your setup and with Vite not with the library. But I'm not sure how to setup Vite properly so it works like in the browser. Since you run the NodeJS version of isomorphic-git from the browser.

**Comment by aral** [comment]
If I remember correctly, Vite uses esbuild and this is an esbuild issue… right found it: https://github.com/vitejs/vite/discussions/2785

https://github.com/evanw/esbuild/issues/1626

**Comment by jcubic** [comment]
@aral thanks for the reference.

**Comment by ninjadev64** [comment]
Hey, I'm using SvelteKit/Vite too :)

But yeah, 
```js
import { Buffer } from "buffer";
globalThis.Buffer = Buffer;
```
seems to be a working solution.

**Comment by jcubic** [comment]
There was an issue #698 but now when @wmhilton left the project there is no one that would remove Buffer from code.

**Comment by StefanR23** [comment]
Until dependencies are removed and if you are working with webpack there is polyfill
https://github.com/Richienb/node-polyfill-webpack-plugin
