### ISSUE TITLE
Getting a 404 with azure devops

### ISSUE THREAD

**Issue by SorenHolstHansen** [isomorphic-git/isomorphic-git#1863]
I am trying to use azure devops for git integration. I am using an [OAuth2 app](https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/azure-devops-oauth?view=azure-devops) to do the authentication, and have given the app all scopes and added it to the repository.

However all remote git commands, e.g. clone, fails with a 404 not found.

For instance, doing this
```ts
const fs = require('fs')
const git = require('isomorphic-git')
const http = require('isomorphic-git/http/node')

const access_token = "<my_token>"

async function main() {
	const res = await git.clone({
		fs, 
		http, 
		onAuth: () => {
			return { headers: {"Authentication": `Bearer ${access_token}`} }
		},
		dir: "./test", 
		url: "https://dev.azure.com/<my_org>/<my_project>/_apis/git/repositories/<my_repo>", 
		ref: "main"
    })
	console.log(res)
}

main()
```

However I am getting the following error
```bash
/Users/.../js_playground/node_modules/isomorphic-git/index.cjs:7086
      throw new HttpError(res.statusCode, res.statusMessage, response)
            ^

HttpError: HTTP Error: 404 Not Found
    at GitRemoteHTTP.discover (/Users/.../js_playground/node_modules/isomorphic-git/index.cjs:7086:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _fetch (/Users/.../js_playground/node_modules/isomorphic-git/index.cjs:7749:22)
    at async _clone (/Users/.../js_playground/node_modules/isomorphic-git/index.cjs:8127:42)
    at async Object.clone (/Users/.../js_playground/node_modules/isomorphic-git/index.cjs:8250:12) {
  caller: 'git.clone',
  code: 'HttpError',
  data: {
    statusCode: 404,
    statusMessage: 'Not Found',
    response: '<!DOCTYPE html >\r\n' +
      '<html>\r\n' +
      '  <head>\r\n' +
      '    <title>Page not found.</title>\r\n' +
      '    <style type="text/css">html {\r\n' +
      '    height: 100%;\r\n' +
      '}\r\n' +
      '\r\n' +
      'body {\r\n' +
      '    font-family: "-apple-system", BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Helvetica, Ubuntu, Arial, sans-serif, "Apple Color Emoji",\r\n' +
      '        "Segoe UI Emoji", "Segoe UI Symbol";\r\n' +
      '    font-size: 14px;\r\n' +
      '    height: 100%;\r\n' +
      '    margin: 0;\r\n' +
      '    background-color: #fff;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.container {\r\n' +
      '    height: 100%;\r\n' +
      '    display: flex;\r\n' +
      '    flex-grow: 1;\r\n' +
      '    flex-direction: column;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.header {\r\n' +
      '    font-size: 14px;\r\n' +
      '    line-height: 20px;\r\n' +
      '    padding-right: 40px;\r\n' +
      '    display: flex;\r\n' +
      '    box-shadow: 0px 1px 0px rgba(0, 0, 0, 0.08);\r\n' +
      '}\r\n' +
      '\r\n' +
      '.header > div,\r\n' +
      '.header > a {\r\n' +
      '    margin: 14px 0px 14px 32px;\r\n' +
      '    text-decoration: none;\r\n' +
      '    color: rgba(0, 0, 0, 0.55);\r\n' +
      '}\r\n' +
      '\r\n' +
      '.header > div:first-child {\r\n' +
      '    flex-grow: 1;\r\n' +
      '    margin-left: 14px;\r\n' +
      '    color: #0078d4;\r\n' +
      '    display: flex;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.header > div:first-child > div {\r\n' +
      '    margin-left: 14px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.content-container {\r\n' +
      '    display: flex;\r\n' +
      '    flex-direction: column;\r\n' +
      '    justify-content: center;\r\n' +
      '    margin-top: 126px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.content {\r\n' +
      '    display: flex;\r\n' +
      '    justify-content: center;\r\n' +
      '    align-items: center;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.error-info {\r\n' +
      '    display: flex;\r\n' +
      '    flex-direction: column;\r\n' +
      '    width: 500px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.title {\r\n' +
      '    font-size: 28px;\r\n' +
      '    font-weight: bold;\r\n' +
      '    line-height: 40px;\r\n' +
      '    letter-spacing: -0.04em;\r\n' +
      '    color: #212121;\r\n' +
      '    margin-bottom: 16px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.details {\r\n' +
      '    font-size: 14px;\r\n' +
      '    line-height: 20px;\r\n' +
      '    color: #212121;\r\n' +
      '    margin-bottom: 16px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.details a {\r\n' +
      '    text-decoration: none;\r\n' +
      '    color: #0078d4;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.reference-data {\r\n' +
      '    font-size: 12px;\r\n' +
      '    line-height: 16px;\r\n' +
      '    color: rgba(0, 0, 0, 0.55);\r\n' +
      '    margin-bottom: 32px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.logo {\r\n' +
      '    height: 500px;\r\n' +
      '    width: 500px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.action-container {\r\n' +
      '    display: flex;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.action {\r\n' +
      '    background-color: #0078d4;\r\n' +
      '    color: #ffffff;\r\n' +
      '    align-items: center;\r\n' +
      '    border-radius: 2px;\r\n' +
      '    border: 1px solid transparent;\r\n' +
      '    cursor: pointer;\r\n' +
      '    display: inline-flex;\r\n' +
      '    flex-direction: row;\r\n' +
      '    flex-shrink: 0;\r\n' +
      '    font-family: inherit;\r\n' +
      '    font-size: inherit;\r\n' +
      '    font-weight: 600;\r\n' +
      '    justify-content: center;\r\n' +
      '    outline: none;\r\n' +
      '    overflow: visible;\r\n' +
      '    padding: 6px 12px;\r\n' +
      '    position: relative;\r\n' +
      '    transition: background 80ms linear;\r\n' +
      '    text-decoration: none;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.action:focus {\r\n' +
      '    box-shadow: 0 0 0 3px rgba(0, 120, 212, 0.35);\r\n' +
      '}\r\n' +
      '\r\n' +
      '.action:hover {\r\n' +
      '    background-color: rgb(0, 103, 181)\r\n' +
      '}\r\n' +
      '\r\n' +
      '.action:active {\r\n' +
      '    background-color: rgb(0, 91, 161)\r\n' +
      '}\r\n' +
      '\r\n' +
      '.secondary-action {\r\n' +
      '    text-decoration: none;\r\n' +
      '    color: #0078d4;\r\n' +
      '    margin-top: 16px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.more-info {\r\n' +
      '    margin: auto;\r\n' +
      '    display: flex;\r\n' +
      '    flex-direction: column;\r\n' +
      '    padding: 0 40px;\r\n' +
      '}\r\n' +
      '\r\n' +
      '.more-info > div:first-child {\r\n' +
      '    font-size: 15px;\r\n' +
      '    font-weight: 700;\r\n' +
      '}\r\n' +
      '</style>\r\n' +
      '  </head>\r\n' +
      '  <body>\r\n' +
      '    <div class="container">\r\n' +
      '      <div class="header">\r\n' +
      '        <div>\r\n' +
      '          <span>\r\n' +
      '            <img class="header-logo" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAGBSURBVHgB5VRBUsJAEOxdYuXgQZ4QPSIH8oP4AvUH8gLiQQleOKHiRXyBX+AH5AdgmUq8EX4QT5Iqk3U2BAlViRHhZlelsjXb0+nszgxQhvargWvHxC/BSxmMaeD8EZY7xZXT2F6QKwfpSkOFj2F5z2h7WhGd5UbbngGIU1oZxMhz5SOOn/BQH2RyNAjRWAnevLUQxQZ5NiBQRbGFgPYnyVPhJCxMMFFd5igJyXIG9MVW4lcUJHNGj7DRq83W/oQJLZujoOOaFGilApQsJmDcBotecFufYENIh10sz+WupmNL8B/P60+CO8a/FGRJNwyxI6w6xRxXoapdGgby1n0q5IC64J2qwE8ZPsJ5gIEefOcsCnuUL5gQaFSxygjlPnxqgCBVaBQLSnRo9gkaV5tCtmn02cyfNpYrXZJbdgERy/dZSQOQ4/AEfd3Pv2U1PE9IXLVxf9zER3gIxE2K2TlsG/NQl2ILo0WQ56nsT9E7mq3HxxrYnkEF0iXXQ/Rrl9ntLw/ghshmZ3a8AAAAAElFTkSuQmCC" />\r\n' +
      '          </span>\r\n' +
      '          <div>Azure DevOps</div>\r\n' +
      '        </div>\r\n' +
      '        <a href="https://go.microsoft.com/fwlink/?LinkID=242573">Service Status</a>\r\n' +
      '        <a href="https://go.microsoft.com/fwlink/?linkid=2119200&amp;clcid=0x409">Support</a>\r\n' +
      '        <a href="https://twitter.com/AzureDevOps">@AzureDevOps</a>\r\n' +
      '      </div>\r\n' +
      '      <div class="content-container">\r\n' +
      '        <div class="content">\r\n' +
      '          <div>\r\n' +
      '            <img class="logo" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA+gAAAPoCAYAAABNo9TkAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAXm8SURBVHgB7N1rzGVZftf3/3puVU/dq7qru7p7umd6prHNYI/Hsp1gjDE2RjgBBESJFGySkFcJKFIEUhR4EQkiRQKUEEcR4kVexEQJiQQkgAHFAWIbbIxjZhh77p6eW/d0d/VUd926rs9t5ay991rrvy77PE/Vc85z9j7n+5l56pyzzz773E/v3/qvtbaxEwIAAAAAABZqTQAAAAAAwMIR0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoAAAAAAAMAAEdAAAAAIABIKADAAAAADAABHQAAAAAAAaAgA4AAAAAwAAQ0AEAAAAAGAACOgAAAAAAA0BABwAAAABgAAjoEAAAAADA4hHQAQAAAAAYAAI6AAAAAAADQEAHAAAAAGAACOgAAAAAAAwAAR0AAAAAgAEgoAMAAAAAMAAEdAAAAAAABoCADgAAAADAABDQAQAAAAAYAAI6AAAAAAADQEAHAAAAAGAACOgAAAAAAAwAAR0AAAAAgAEgoAMAAAAAMAAEdAAAAAAABoCADgAAAADAABDQAQAAAAAYAAI6AAAAAAADQEAHAAAAAGAACOgAAAAAAAwAAR0AAABHYq0AAOaIgA4AAIAjMUYAAHNEQAcAAAAAYAAI6AAAADiU695u1XkAwOwR0AEAANDLZ/Gme7vNlwIAZomADgAAgCoXw5NcbrrqOYPRAWAuCOgAAACoCjFcFcx9JZ1u7gAwexsCAAAA9GhyuCqYW5teBgDMDhV0AAAA9LPCkHMAOCEEdAAAAFTpbuzWB3Uj9G8HgDkhoAMAAKCu1pXdUlAHgHkhoAMAACDwxXHr/zESg3oI7IaUDgBzQEAHAABAw2an+RW2S+8m/AMAmCUCOgAAAELF3B1GTRfKYym9XWBjWhcAwGxxmDUAAACEqnibx/NjqfnzdnKu6O8OAJgRKugAAABohJq4MWqZVadtBd1y7DUAmAsCOgAAAMJ8cDF75wE8r6hTQQeAWSOgAwAAIGH9YHR9uTunBqYDAGaMgA4AAIA2dneVc2OMOt65Ydw5AJwQAjoAAAAUHc7b/u7UywHgZDCLOwAAwIrrP2JarWJuhUo6AMwHFXQAAAC0utxdr5mrY6FbZnEHgHkgoAMAAKywJmYbfUEv0GuZ7lw3Rp0qOgDMHAEdAABgxemo3QTw7lx7oru0WzVhHABg1gjoAAAAKywP5+2pXiFWzm3I7HRvB4B5IKADAACsMJe1fd5Oq+PxeOdWVc6J5gAwPwR0AACAVWbyizGYh5BuVTCneg4Ac8Nh1gAAANCI0bsN5kkUz4I5B1sDgNmjgg4AALCirPqnPLSaaa5zFXVjiOIAcBII6AAAAKsqK4Ob7EoXzN2EcGl0N2HiOADAbBHQAQAAVpZVB0I3SRBvJo/Th1oz6mDpTXd3xqIDwKwR0AEAAFaWSU7a0G3jsjyxq7UAALNHQAcAAFgxIYZ3wTw9zFrbrT2mcFOcmuQyAGBWCOgAAAArxkiM11ZVzfW/SZd2JU4nRx0dAGaNgA4AALCC2snb9fHO26VWTxxnuijvTk0+pxwVdACYNY6DDgAAsGLi4dVMNtTcHVKtC+mqTm5Uj/d0JDohHQBmiQo6AADAijHhHxtP847rRh9OTdfNy2UAgNmggg4AALBiQoW8O865n7Ld+sOuuWDeHf/cNIdf03VzXUsnpAPALBHQAQAAVkyTv/2g8mx2dtv804Z3U8wD5zvEE8wBYB4I6AAAACvEqjPV8eS+om5rc7UzczsAzBNj0AEAAFaIUWd0Hbzp4N5VzrNp49Qt64deAwDMBgEdAABghYQJ2m0yT7sK4ofdmpAOAPNCQAcAAFhpacU8LjNdju+us2pyuGTsOgBgVgjoAAAAK8IW560U4dy2h16z+fJsiDoAYPYI6AAAACvIqH99tTwc99zaYk1rw+TuUq+6j4u16oBx9NYHMBAEdAAAgBWhJ4iL8dQfC116kmq7zHRzxLVBffxldGOMqJeAkA5gEAjoAAAAqyT0aq8FbBNWCaur7G7S1UZLh3F67AMYEgI6AADAipg6t5v1yd3P6N51gu/WNyafJ27EJWejXgvLfPQAhoOADgAAsCpUEg0HS/OlceOr57YL3zZWz6XsAm5GWHe2+oxVXfcBYCAI6AAALBDjXnHibHIS53urfBhD1dz6yybO5i7jE6a28xPd2fT5AcCiEdABAFiAPAv15CNgpsJEb/rwamEQtslyatrFvVnVqv7gI/3ANk/H6gsiqkc/ACwUAR0AgAVoK5M2jIUNR64C5siGf8orXGg3SVJtu7gnlfaRK+bHs113fqroAAaCgA4AwAnRs2HbeEDpttstAQEnoZK2jf8cqs9j7NKu1rSVzYxIqP777ipdq9gYx9IDWF4bAgAA5s4fNjoEc2vS64o+t8B82OxSbDhKZ5ALhzpfgoajtmreP3g+9GIBgAWjgg4AwByF2O0rkcbE7uxJJc8vBObDJufaSGr7urv7Dh6Vqvmou7yHxjCTBfVRHzQOwBIhoAMAMCe+S631f2G5xKBg/CB0wjlOhtHdupuWI5NcKyY75nm8JjWSRBuq40ljg1UNDkvUVQDA6BHQAQCYEzem1+gBvMU4c5OWJcnomCd9TPOwzIZl+VjsWpvRWAdi1Ganj1VzvngAhoOADgDAjPlJ4HwP9tCnvTikk02zAQU8zJNJTsJRBGJIj9Hd9/rQbM/5wctaFcpQ3j5vJosDMAQEdAAAZsz4QJ6nGN2T1sZ1Qmdb8gFOjI2fU8niqi17vY+RzYN534D7biVGoQMYAgI6AAAzFMeaq9BdKz0moacNB5Z8gDlppzzQH7BugjibfFrba0xsP9JXmmKD42Ka75lj9UHmJH5JaSEDsHgEdAAAZqnrMmxqh3QKi1SX4qznOzAPvk4e5yfMR2Vnnz41UL2YvT1ucNBCQ4NqiOiuYWI4AINFQAcAYNaMyQ5p1Z0Lh1SL3d99xd0YuthiftLKcdcwpPqx2+Rzmt+ud4ODljZEGFUjL6vlNiR5AFgsAjoAADNQFOn0waKz+ajS7rVWz9MFzJFRE6TpKnKsoPcdWs2WmxoHo79/NnnO6XpCPgcwCAR0AACOSWfxhMkv+i7GNp0xuz4wHZiZ8hjmVvX/znpvVEZn1BcMWzj2efEF7Xkihu8fgMUjoAMAMEs+EHQVOdv+U6nd1abJpoSH+SiGXBTd202xcigqq/aj5vCBI+nermdxz0fcp+uq8SYAsGAEdAAAjiEcuimfDC4Zx6tHv/Z0sQ03BOagt5tHukI6Ll3dJBwX3Yyj0FwMN0laG'... 123987 more characters
  }
}
```
I am getting the error both in node and in the browser.

Looking at the browser network tab, I can see that it calls the following endpoint `https://dev.azure.com/<my_org>/<my_project>/_apis/git/repositories/<my_repo>/info/refs?service=git-upload-pack` which I can't find any documentation on, I can only find `https://dev.azure.com/<my_org>/<my_project>/_apis/git/repositories/<my_repo>/refs`, but not sure if that is the error

**Comment by SorenHolstHansen** [comment]
Alright, nvm found out I was using a wrong url. It is supposed to be `https://dev.azure.com/<my_org>/<my_project>/_git/<my_repo>`
