### ISSUE TITLE
Encountering unknown error, Invalid checksum in GitIndex

### ISSUE THREAD

**Issue by ahmadkani** [isomorphic-git/isomorphic-git#1953]
I'm using service worker for caching. I clone a repo and then cache its files by reading files and its contents using lightning fs and then retrieve the files using lightning fs write file and mkdir. but after retrieving all files including .git files, when I try to pull I encounter this error : 

Git operation failed: Error: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 360a094c0507efbfbdefbfbddaadefbfbd79d195 but saw 5d916950a94408e79d89c23bc4553fa009f86c31
    at pull (service-worker.js)
    at async handleGitRequest (service-worker.js:202:20)

or when I try to fetch I face this error : 
script.js:208 Uncaught (in promise) An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: Invalid checksum in GitIndex buffer: expected 360a094c0507efbfbdefbfbddaadefbfbd79d195 but saw 5d916950a94408e79d89c23bc4553fa009f86c31

also when I clone after cloning first time it works very well but when I refresh the page I encounter this error:
Error in log: TypeError: Cannot read properties of undefined (reading 'error')
    at IsomorphicGit.js:8:112002
    at Generator.next (<anonymous>)
    at a (IsomorphicGit.js:8:111378)
    at s (IsomorphicGit.js:8:111581)

what can be the problem, I have NOOOO idea. if this approach is wrong what else I can do?

**Comment by jcubic** [comment]
Do you have the code somewhere online, where I can look it up? You can try to publish your code to GitHub so we can test it locally.

**Comment by ahmadkani** [comment]
I uploaded the service worker code on this public repo : https://github.com/ahmadkani/isomorphicGit-SW
it's actually a part of a big project and the git part is just a web worker that handles network requests like cloning and pushing , ... with service worker. but the main problem is in this service worker which handles clone, pull, fetch and push.
I guess writing the files and their contents to the idb is somehow faulty, because the output uint8arrays in idb is different from the one that is cloned from network but the output contents are identical.

**Comment by jcubic** [comment]
So when I was playing with Service Worker I did clone in the main thread not in Worker.

Ask yourself do you really need to clone in Service Worker? I don't think that Service Worker was designed to make heavy processing. But if you want to not process in main thread you can use web worker for the clone and Service Worker only for stuff related to HTTP requests.

**Comment by jcubic** [comment]
You can try to create minimal reproduction of the issue. There is a lot of code and no way to test it. I may create a repro myself, but I don't have much time to create this for you. It may take a while before I will have time to do this.

**Comment by ahmadkani** [comment]
Yeah, my first version of code was only web worker but now its main Thread, web worker and service worker. I wanted to take clone to service worker because it’s more safe and secure. But my main problem is for the caching and retrieving the cash and write the whole repo to indexed db again. With I will need for my pwa and it’s sync ability, don’t you have something in mind for doing this process neat and nice? So I don’t have to face this git index differing bug?

**Comment by jcubic** [comment]
I don't understand how Service Worker is more secure. SW was not created to process data only to handle HTTP requests, that's why you may have problem with it. But without a reproduction that I can actually test, and not spend few hours to remove stuff that are not needed and create the project that will work, Nothing I can do.
