### ISSUE TITLE
Error git cloning, if a file larger than ~5mb in repo

### ISSUE THREAD

**Issue by gnillev** [isomorphic-git/isomorphic-git#1954]
Using Browser (with Lightning FS).

Received the following error from `Pako` when trying to clone a repo having a file ~6mb (explicit one-of test case I did):
```
Error cloning git repo InternalError: An internal error caused this command to fail. Please file a bug report at https://github.com/isomorphic-git/isomorphic-git/issues with this error message: 
Pako error: invalid distance too far back
    at listpack (index.js:2621:15)
    at async GitPackIndex.fromPack (index.js:2821:5)
    at async _fetch (index.js:8296:17)
    at async _clone (index.js:8419:42)
    at async Object.clone (index.js:8545:12)
```

The annoying part is also, even after deleting the file in the repo, I still can't clone "past" the commit with the large file.
I.e. I tested deleting the file, and doing a normal clone - which still failed. 
Then I did a clone with `depth: 1`, which succeeded - but of course, I only have the latest commit (deleting the large file) locally.

It may be an edge case, but reporting it as prompted ;)
(Also 5mb isn't **that** large.)

**Comment by jcubic** [comment]
Can you create a reproduction that you can test? Also note that this project is community driven so if you're the only person that have this, but it may never get fixed unless you try to debug it and maybe create a PR.

**Comment by gnillev** [comment]
Yeah, it is an edge-case - also for us - but I will try to see if I get time to create a reproducing test.
I'm mainly reporting "as requested" by the error message wrapper, but it is probably not a common case for most repos.

**Comment by jcubic** [comment]
We had a lot of issues with that error message some time ago. The Salesforce CLI app broke and we got a flood of people who use Salesforce that were reporting bugs, some of them without any context. Just because of the error message said to do this.
