### ISSUE TITLE
Git pull from empty repository.

### ISSUE THREAD

**Issue by Noirox** [isomorphic-git/isomorphic-git#1967]
Browser:
`Chrome Version 130.0.6723.93 (Official Build) (arm64)` 
with 
`@isomorphic-git/lightning-fs:4.6.0` 
`isomorphic-git:1.26.3`

In our situation, we're encountering an issue where the pull operation fails with the error message Could not find master., even though the remote repository does contain a master branch with commits.

```js
Could not find master.
    at GitRefManager.expand (index.js:2063:1)
    at async _merge (index.js:9568:1)
    at async _pull (index.js:9773:1)
    at async Object.pull (index.js:12129:1)
    at async gitPull (gitUtils.ts:156:1)
```

The issue appears to stem from the fact that our remote repository is set up as a bare repository. While it can be successfully cloned and pushed to, if this repository is updated through other ways, the first clone (at that moment origin was empty) will encounter failures during a pull operation. Similarly, performing a fetch operation (which completes without error) followed by a pull will result in the same failure.

Steps to reproduces:
1. have git bare repository
2. create clone A
3. create clone B
4. cloned B - commits/push to the origin successfully
5. cloned A - fails during doing `pull` or doing `fetch` first and then `pull` again

**Comment by jcubic** [comment]
Can you create a small reproduction that I can run?

**Comment by Noirox** [comment]
> Can you create a small reproduction that I can run?

I'm not sure if I can completely. 
https://codesandbox.io/p/sandbox/peaceful-rubin-jst36h

1. in that sandbox edit App.tsx:14 to some empty git repository under your control
2. now if you click on the button `do git pull` it will fail, in this case its expected
3. update repository without doing anything in the sandbox app, thats important (like thru terminal) commit and push
4. click again on the button `do git pull`
5. in the fetch result it should be visible updated result
6. yet the git pull fails with same error

hope it helps, or if you have any other idea how can I provide you e2e sample, I'm one ear :)

**Comment by jcubic** [comment]
I don't understand how you can have an empty git repository and yet have a branch and commits. Should I delete all the files? Can you create such a repository?

**Comment by Noirox** [comment]
> I don't understand how you can have an empty git repository and yet have a branch and commits. Should I delete all the files? Can you create such a repository?

I'm sorry, I didn’t mean it at the same time.

You start with an empty repository.

Then, you clone the empty repository in the browser and leave it open there. Then, using a different Git client, you make a commit and push it to the repository, so it’s no longer empty.

Now, if you go back to the browser with the cloned repository and attempt to pull the changes, you’ll see that error message. This happens even if you try to fetch first and then pull.

**Comment by jcubic** [comment]
I never heard of closing empty repository, does it work with canonical git?

**Comment by Noirox** [comment]
> I never heard of closing empty repository, does it work with canonical git?

Yes, you can do it like this:
```sh
mkdir sourceRepo 
cd sourceRepo

git init --bare

cd ..

git clone sourceRepo repoA
git clone sourceRepo repoB

cd repoA

touch a.txt
git add .
git commit -m "first"
git push

cd ..

cd repoB
git pull
```

**Comment by jcubic** [comment]
The problem is that with isomorphic git, when you pull, you do fetch and merge. And if there are no branches locally, you can't merge. Canonical git do something different when repo is empty.

Unfortunately, this project doesn't have a main author that will do all the coding to fix the issue for you. This project is community driven, so you need to find someone that will fix the issue for you, or you can solve the issue yourself by contributing.

**Comment by Noirox** [comment]
> The problem is that with isomorphic git, when you pull, you do fetch and merge. And if there are no branches locally, you can't merge. Canonical git do something different when repo is empty.
> 
> Unfortunately, this project doesn't have a main author that will do all the coding to fix the issue for you. This project is community driven, so you need to find someone that will fix the issue for you, or you can solve the issue yourself by contributing.

That’s a fair point. I mainly wanted to use this issue as an opportunity to check whether this behavior is considered a bug or not, like if aligning it closer to canonical Git would be seen as a worthwhile improvement for the project. ;)

**Comment by jcubic** [comment]
If you know how to make this work, you can contribute. I'm not even sure what is the right thing in this case.

**Comment by jcubic** [comment]
Sure go ahead.
