### ISSUE TITLE
broken ref

### ISSUE THREAD

**Issue by jcubic** [isomorphic-git/isomorphic-git#243]
So I did this:

1. git clone
2. git reset --hard HEAD~1 (from #129)
3. git pull

and my gitBrach function was broken the same as git.currentBranch which return:
```
ref: refs/heads/master
```
It looks that the reset was correct and I had correct results.

Got this in console:
```
Using ref=ref: refs/heads/master
Performing a fast-forward merge...
Uncaught (in promise) Error: Could not resolve reference refs/heads/ref: refs/heads/master
```

**Comment by jcubic** [comment]
after this `.git/HEAD` had `ref: refs/heads/ref: refs/heads/master` inside.

**Comment by jcubic** [comment]
The fix is to use in code:

```
await git.pull({
    fs,
    dir,
    ref: await git.currentBranch({fs, dir}),
    singleBranch: true,
    ...auth,
    emitter: messageEmitter()
});
```

git.currentBranch should be used instead of:

```
  if (!ref) {
    ref = await GitRefManager.resolve({
      fs,
      gitdir,
      ref: 'HEAD',
      depth: 1
    })
  }
```

or there should it should be `ref.replace(/^ref:\s*/, '');`

**Comment by jcubic** [comment]
It seems that this don't work await git.currentBranch({fs, dir}) nor:
```
var ref = await git.resolveRef({
                        fs,
                        dir,
                        ref: 'HEAD',
                        depth: 1
                    })
                    await git.pull({
                        fs,
                        dir,
                        ref: ref.replace(/^ref:\s*/, ''),
                        singleBranch: true,
                        fastForwardOnly: true,
                        ...auth,
                        emitter: messageEmitter()
                    });
```

**Comment by jcubic** [comment]
`git.pull` seems broken. I've cloned the repo in browser commit from terminal, run git pull and nothing changed. also HEAD before and after `git.pull` point to the same commit.

**Comment by wmhilton** [comment]
There's a bug in your `git reset --hard HEAD~1` implementation. You shouldn't be seeing messages like `already merged into 'ref: refs/heads/master'` is should say `already merged into 'refs/heads/master'`. Most likely that's because you're using resolveRef({ref: 'HEAD', depth: 1}) instead of resolveRef({ref: 'HEAD', depth: 2}).

Because `resolveRef({ref: 'HEAD', depth: 2})` is such a ridiculously obscure command to remember, and the depth thing is kinda funky and arbitrary, I made a better command yesterday (I think) called [`currentBranch`](https://isomorphic-git.github.io/docs/currentBranch.html) that you can use instead.

There may also be a bug in `git pull`. It'll be easier to debug once you've got the messed up `ref: refs/heads/ref: refs/heads/master` stuff fixed.

**Comment by TomasHubelbauer** [comment]
Is the code block in the docs of that new method okay? The comment seems to be a copy-paste error (or I totally failed to parse it) and the return value is never used.

**Comment by jcubic** [comment]
The problem is that I don't do `resolveRef({ref: 'HEAD', depth: 1})` the error happen in just clone + pull when I push from other client.

Also when I reset and run git log I don't have last commit and I have correct branch name. so I think that my `git reset` is ok.

**Comment by wmhilton** [comment]
@TomasHubelbauer thank goodness I have you guys, keeping my honest LOL! I'll fix the docs.

> The problem is that I don't do resolveRef({ref: 'HEAD', depth: 1}) the error happen in just clone + pull 

@jcubic Well, _somebody_ must be calling `resolveRef({ref: 'HEAD', depth: 1})` to get that error... Oh look, it's me! 🤦‍♂️ 

https://github.com/isomorphic-git/isomorphic-git/blob/master/src/commands/pull.js#L31

**Comment by wmhilton** [comment]
Hmm. Well I fixed one problem but may have discovered another. I'm getting those empty packfiles again (`.git/objects/pack/pack-.pack`). But at least now the problem is in `fetch` and not `pull`.

**Comment by wmhilton** [comment]
>  I've got console.log message:
>
> 'fd4588d04888596af9215d4897835bf475769212' is already merged into 'ref: refs/heads/master'
> but it should throw exeception/reject promise.

No need to throw an error because "already merged" is a successful merge. I just have those in there as diagnostic messages at the moment, to help debug `merge` because it's new.

**Comment by jcubic** [comment]
Also it seems that there are no tests for `git.pull`.

**Comment by wmhilton** [comment]
> Also it seems that there are no tests for git.pull.

[Why does everyone keep saying that?](https://github.com/isomorphic-git/isomorphic-git/blob/1977e0b560be33361157045f21e554cd0a1e6b8c/__tests__/server-only.test-pull.js)

**Comment by jcubic** [comment]
I've now cloned new repo (depth: 2) have checkout branch gh-pages (fetch depth: 1) pushed one commit to that branch from real git client and I've tried then to pull from browser and it hands. And the same happen to git log, I didn't have my reject from #254

**Comment by jcubic** [comment]
I've tested again version 0.18.2 with clone+fetch+checkout (commmit to checkout branch) + pull and got exception this time:
```
Failed to read git object with oid db0ccbda6ad13fcf471bdda7370ee9b56fd6c16c
Error: Failed to read git object with oid db0ccbda6ad13fcf471bdda7370ee9b56fd6c16c
    at https://cdn.jsdelivr.net/npm/isomorphic-git@0.18.2/dist/bundle.umd.min.js:8:30278
    at Generator.next (<anonymous>)
    at n (https://cdn.jsdelivr.net/npm/isomorphic-git@0.18.2/dist/bundle.umd.min.js:8:28961)
    at https://cdn.jsdelivr.net/npm/isomorphic-git@0.18.2/dist/bundle.umd.min.js:8:29055
```
when I pause the execution on exception I've got error:

```
Error: ENOENT: No such file or directory., '/test/.git/packed-refs'
```

**Comment by wmhilton** [comment]
Which repo is this? I'm wondering there's something different about db0ccbda6ad13fcf471bdda7370ee9b56fd6c16c.

I think `no such file or directory., '/test/.git/packed-refs'` is a red herring, but I'll double check that. Clone should have created a packed-refs file...

**Comment by jcubic** [comment]
I'm using my test repo https://github.com/jcubic/test and test branch that I've pushed commit into.

**Comment by jcubic** [comment]
Freeze was on my Git Web Terminal repo https://github.com/jcubic/git but to recreated it I use my test repo because I don't need to care what I push there.

**Comment by jcubic** [comment]
Git error internal error with message `invalid type passed to GitTree constructor` from pull

**Comment by wmhilton** [comment]
Are you sure that error is not coming from `git.status`? I just looked at all the places that could POSSIBLY have thrown that error, and the only place I'm not checking what I pass to the GitTree contructor is in face a tree is in the `getHeadTree` function in git status.

**Comment by jcubic** [comment]
I'm running commit diff for HEAD before and after pull, I'm using this code:
```
var HEAD_after = await git.resolveRef({fs, dir, ref: 'HEAD'});
const diffs = await gitCommitDiff({fs, dir, oldSha: HEAD_before, newSha: HEAD_after});
```

If I run git diff I also get the same error, and that one came from `git.status`.

Here are the functions I'm using:

```
async function traverseCommit({fs, dir, sha, callback = $.noop}) {
    const repo = {fs, dir};
    const { object: { tree } } = await git.readObject({ ...repo, oid: sha });
    return await (async function readFiles(oid, path) {
        const { object: { entries } } = await git.readObject({ ...repo, oid});
        var i = 0;
        return (async function loop() {
            var entry = entries[i++];
            if (entry) {
                if (entry.type == 'blob') {
                    var filepath = path.concat(entry.path).join('/');
                    await callback({entry, filepath, oid: entry.oid});
                } else if (entry.type == 'tree' && entry.path !== '.git') {
                    await readFiles(entry.oid, path.concat(entry.path));
                }
                return loop();
            }
        })();
    })(tree, []);
}

// ---------------------------------------------------------------------------------------------------------
async function gitCommitDiff({fs, dir, newSha, oldSha}) {
    var result = {};
    function reader(name) {
        return async ({filepath, oid}) => {
            try {
                const { object: pkg } = await git.readObject({ fs, dir, oid });
                result[filepath] = result[filepath] || {};
                result[filepath][name] = pkg.toString('utf8');
            } catch(e) {
                // ignore missing file/object
            }
        };
    }
    await traverseCommit({fs, dir, sha: oldSha, callback: reader('oldFile')});
    await traverseCommit({fs, dir, sha: newSha, callback: reader('newFile')});
    Object.keys(result).forEach(key => {
        var diff = JsDiff.structuredPatch(key, key, result[key].oldFile || '', result[key].newFile || '');
        if (typeof result[key].oldFile === 'undefined') {
            result[key].added = true;
        } else if (typeof result[key].newFile === 'undefined') {
            result[key].deleted = true;
        } else if (!diff.hunks.length) {
            delete result[key];
        }
        if (diff.hunks.length) {
            result[key].diff = diff;
        }
    });
    return result;
}
```

And when I refreshed the browser after I've added try catch with debugger so see which filepath throw exception the error go away and git log show last commit. Will try the same steps again later Today.

**Comment by wmhilton** [comment]
That's some pretty nice code @jcubic !! Hopefully we can integrate a diff lib into isomorphic-git soon so we can efficiently generate diffs. You're method is a little brute force; you're reading all the files into memory first, then diffing, instead of selectively diffing files whose SHA1s differ.

`invalid type passed to GitTree constructor`... I wish I knew what was passed to the constructor. Why did I write an error message that just says it is invalid? I should have included `typeof tree` or something. The most likely candidate is "undefined"... lemme double check my `readObject` code.

You didn't clone a repo with submodules by any chance did you?

**Comment by wmhilton** [comment]
Hah! There is! There's an odd case in readObject where if the `tree` object of a commit is an OID that can't be found, it slips through the `"type"` checking and gets passed straight to the constructor. Now how you obtained a repository state where you have a commit where the tree is inaccessible... I don't know. But one bug at a time.

**Comment by jcubic** [comment]
I check all the commits because git.status only show status between working tree and HEAD, or is it a way to check status between two commits? My diff when I call git diff is much simpler it first run git status and run diff on files that differ.
