### ISSUE TITLE
"npm run build" fails to minify

### ISSUE THREAD

**Issue by jchamath** [isomorphic-git/isomorphic-git#333]
I used isomorphic-git in my node project. "npm start" works fine. But, when trying to make a build with "npm run build", it fails due to a failure to minify isomorphic-git. Here's the log.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.1.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle sigma@1.0.0~prebuild: sigma@1.0.0
6 info lifecycle sigma@1.0.0~build: sigma@1.0.0
7 verbose lifecycle sigma@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle sigma@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/Chamath/Code/MyProject
/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/opt/gc-sdk/google-cloud-sdk/bin:/Users/Chamath/.rvm/gems/ruby-2.2.5/bin:/Users/Chamath/.rvm/gems/ruby-2.2.5@global/bin:/Users/Chamath/.rvm/rubies/ruby-2.2.5/bin:/opt/jdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/gradle/bin:/opt/maven/bin:/Users/Chamath/.bin/:/opt/grails/bin:/opt/elasticsearch/bin:/opt/kibana/bin:/opt/scala/bin:/usr/local/mysql/bin:/opt/groovy/bin:/Users/Chamath/Library/Python/3.6/bin:/Users/Chamath/.rvm/bin
9 verbose lifecycle sigma@1.0.0~build: CWD: /Users/Chamath/Code/MyProject
10 silly lifecycle sigma@1.0.0~build: Args: [ '-c', 'node scripts/build.js' ]
11 silly lifecycle sigma@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle sigma@1.0.0~build: Failed to exec build script
13 verbose stack Error: sigma@1.0.0 build: `node scripts/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid sigma@1.0.0
15 verbose cwd /Users/Chamath/Code/MyProject
16 verbose Darwin 17.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v8.11.1
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error sigma@1.0.0 build: `node scripts/build.js`
22 error Exit status 1
23 error Failed at the sigma@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
~
```

After going through some documentation, found [this](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify). Is this a possibility?

**Comment by wmhilton** [comment]
From the log it looks like a package called "sigma" is the problem, not isomorphic-git. What tool are you using to build?
