### ISSUE TITLE
git.fetch documentation code example crashes

### ISSUE THREAD

**Issue by kpj** [isomorphic-git/isomorphic-git#738]
When trying to run the code block on the [git.fetch](https://isomorphic-git.org/docs/en/fetch.html) documentation webpage, I get the following error (happens in both Chrome and Firefox):
```javascript
name: "TypeError"
message: "Cannot read property 'split' of null"
stack: "TypeError: Cannot read property 'split' of null
    at new b (https://unpkg.com/isomorphic-git@0.55.2/dist/bundle.umd.min.js:8:64118)
    at Function.from (https://unpkg.com/isomorphic-git@0.55.2/dist/bundle.umd.min.js:8:64353)
    at https://unpkg.com/isomorphic-git@0.55.2/dist/bundle.umd.min.js:8:28034
    at Generator.next (<anonymous>)
    at o (https://unpkg.com/isomorphic-git@0.55.2/dist/bundle.umd.min.js:8:27621)
    at s (https://unpkg.com/isomorphic-git@0.55.2/dist/bundle.umd.min.js:8:27823)"
fileName: undefined
lineNumber: undefined
columnNumber: undefined
```

I get the same error when trying to run `git.fetch` in the browser with my own project.

As a side note: is using `git.fetch` the recommended way of retrieving the commits of a large repository (large == many commits) in a paginated way, when the end goal is to compare files between adjacent commits in an efficient way?

**Comment by TomasHubelbauer** [comment]
@wmhilton sorry if this question has an obvious answer I am not realizing, but why not ship source maps with the minified source code in the package? I am asking because the stack trace provided goes to the minified code, so it makes it harder to debug. If there is a concern about package size, maybe there could be another dev build, like React does, so that when users run into issues, they may be asked to swap out of the deb build to see readable stack traces - and such dev build could also be used on the examples site.

**Comment by kpj** [comment]
As it might help: in my own project I get the following (non-minified) error:
```javascript
Uncaught (in promise) TypeError: Cannot read property 'split' of null
    at new b (GitConfig.js:127)
    at Function.from (GitConfig.js:149)
    at _callee33$ (GitConfigManager.js:10)
    at tryCatch (runtime.js:65)
    at Generator.invoke [as _invoke] (runtime.js:303)
    at Generator.prototype.<computed> [as next] (runtime.js:117)
    at o (dirname.js:1)
    at s (dirname.js:1)
```
I assume it is the same one.

**Comment by TomasHubelbauer** [comment]
Interesting! Does `.git/config` exist in the repo you are attempting to fetch? It looks like `GitConfigManager` is reading the file okay, because `read` does not throw, but later when the text is propaged to the `GitConfig` model constructor, it is `null`. It depends on the actual file system implementation, you are probably using the default one, but I am not familiar with the FS impls enough to be able to tell why it returns `null`.

**Comment by kpj** [comment]
I think that neither `.git/config` nor `.git/` exist, because I am trying fetch commits from a remote repository which does not exist locally.
This is the relevant code:
```javascript
import FS from '@isomorphic-git/lightning-fs'
const git = require('isomorphic-git')

const fs = new FS('fs', { wipe: true })
git.plugins.set('fs', fs)
const pfs = fs.promises

const dir = '/repo'
await pfs.mkdir(dir)

const res = await git.fetch({
  dir: dir,
  corsProxy: 'https://cors.isomorphic-git.org',
  url: repoUrl,
  ref: branch,
  singleBranch: true,

  depth: 1
})
```

**Comment by jcubic** [comment]
I think that you can't just fetch the commits, you need to have git repository to do this, so you first need to clone the repo, or create new one and add remote and then fetch (not sure about the last one).

**Comment by kpj** [comment]
Hmm, I must have misunderstood the documentation (of `git.fetch`) then. It says: "Fetch commits from a remote repository", which I thought is exactly what I want.

What would then be the recommended way of retrieving the files of each commit while tracking progress?
`git.clone` supports the ['emitter' plugin](https://isomorphic-git.org/docs/en/plugin_emitter) but `git.log` does not. At the moment, I once have to wait to clone the repository and then once again while retrieving commit descriptions (which I need to get the files per commits).
