### ISSUE TITLE
Tests fail under node+windows

### ISSUE THREAD

**Issue by tripodsan** [isomorphic-git/isomorphic-git#783]
with node 10.16.0 in windows, running the tests fail, mostly dues to path separator errors:

```
Summary of all failing tests
 FAIL  __tests__/test-utils-join.js
  ● utils/join › should join "good" paths the same as path.join

    expect(received).toEqual(expected)

    Expected value to equal:
      "\\foo\\bar\\baz"
    Received:
      "/foo/bar/baz"

      20 |     ]
      21 |     for (const fixture of fixtures) {
    > 22 |       expect(join(...fixture)).toEqual(path.join(...fixture))
         |                                ^
      23 |     }
      24 |   })
      25 |   it('should join degenerate paths the same as path.join in these cases', async () => {

      at Object.toEqual (__tests__/test-utils-join.js:22:32)

  ● utils/join › should join degenerate paths the same as path.join in these cases

    expect(received).toEqual(expected)

    Expected value to equal:
      "foo\\x\\bar"
    Received:
      "foo/x/bar"

      55 |     for (const [args, result] of fixtures) {
      56 |       expect(join(...args)).toEqual(result)
    > 57 |       expect(join(...args)).toEqual(path.join(...args))
         |                             ^
      58 |     }
      59 |   })
      60 |   it('should join degenerate paths differently from path.join in these cases', async () => {

      at Object.toEqual (__tests__/test-utils-join.js:57:29)


Test Suites: 1 failed, 61 passed, 62 total
Tests:       2 failed, 2 skipped, 267 passed, 271 total
Snapshots:   83 passed, 83 total
Time:        45.033s
```

**Comment by wmhilton** [comment]
It _should_ be fixed... but my Windows computer is borked at the moment so I didn't get to actually test it. Lemme know if the tests still fail.
