### ISSUE TITLE
Doc Examples are Broken

### ISSUE THREAD

**Issue by fuzzyTew** [isomorphic-git/isomorphic-git#912]
Try running the example at https://isomorphic-git.org/docs/en/resolveRef .  For me it outputs:
```
o {name: "ResolveRefError", message: "Could not resolve reference "HEAD".", stack: "ResolveRefError: Could not resolve reference "HEAD".
    at https://unpkg.com/isomorphic-git@0.70.1/dist/bundle.umd.min.js:1:21295
    at Generator.next (<anonymous>)
    at f (https://unpkg.com/isomorphic-git@0.70.1/dist/bundle.umd.min.js:1:18184)
    at a (https://unpkg.com/isomorphic-git@0.70.1/dist/bundle.umd.min.js:1:18386)", fileName: undefined, lineNumber: undefined…}
name: "ResolveRefError"
message: "Could not resolve reference "HEAD"."
stack: "ResolveRefError: Could not resolve reference "HEAD".
    at https://unpkg.com/isomorphic-git@0.70.1/dist/bundle.umd.min.js:1:21295
    at Generator.next (<anonymous>)
    at f (https://unpkg.com/isomorphic-git@0.70.1/dist/bundle.umd.min.js:1:18184)
    at a (https://unpkg.com/isomorphic-git@0.70.1/dist/bundle.umd.min.js:1:18386)"
fileName: undefined
lineNumber: undefined
columnNumber: undefined
```

**Comment by wmhilton** [comment]
It works for me if I run the `clone` example first. Maybe I should add a note to the docs suggesting that?

**Comment by fuzzyTew** [comment]
I'd forgotten I reported this and felt responsible, so I found https://github.com/isomorphic-git/isomorphic-git.github.io/blob/source/website/static/js/tutorial.js that runs the evaluation.

What do you think of a code addition to catch errors, report them, and then handle the first failure by wiping the fs, cloning, and trying again?  Or maybe just to clone first if the fs is empty?  I almost started implementing something like one of those, but I noticed you code in a very generic way and I wasn't sure if you'd want the `clone` code hardcoded into that file.

**Comment by wmhilton** [comment]
No, I don't think I would want to automatically run clone. But maybe isomorphic-git should be smart enough to throw a `NotAGitRepoError` error in functions other than `clone`, `init`, and `getRemoteInfo`.

**Comment by wmhilton** [comment]
Then if we wanted, we could customize the handling of `NotAGitRepoError` in the website and include a nice message like "I couldn't find a git repo at {gitdir}. Perhaps you would like to run the [`clone`](./clone.md) example?"
