### ISSUE TITLE
Can't go checkout without remote

### ISSUE THREAD

**Issue by outerdev** [isomorphic-git/isomorphic-git#947]
I'm working on a node project and I may have circumstances where the repo I'm manipulating with isomorphic-git does not have a remote.
When I attempt to checkout a branch without a remote I get the following error:

> UnhandledPromiseRejectionWarning: ResolveRefError: Could not resolve reference "origin/dev".

I suppose the code is just adding the origin assuming that it's supposed to be there but in my case it isn't there and it won't be. Suggestions on how to mitigate the issue or should I workup a PR?

**Comment by CharlieLau** [comment]
```
await git.branch({
        dir,
        ref: '**'
    })
    await git.checkout({
        dir,
        ref: '**'
    })
``

**Comment by wmhilton** [comment]
It only looks for `origin/dev` if it cannot find `dev` first. Can you paste a reproduction?

**Comment by lipeavelar** [comment]
@wmhilton the documention reproduces the error: https://isomorphic-git.org/docs/en/checkout

```
i {name: "NotFoundError", message: "Could not find origin/master.", stack: "r@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:5118
i@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:12811
resolve/<@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:9174
l@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:6229
a@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:6433
", fileName: "https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js", lineNumber: 1…}
name: "NotFoundError"
message: "Could not find origin/master."
stack: "r@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:5118
i@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:12811
resolve/<@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:9174
l@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:6229
a@https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js:1:6433
"
fileName: "https://isomorphic-git.org/js/isomorphic-git/index.umd.min.js"
lineNumber: 1
columnNumber: 5118
```

**Comment by JustinBeckwith** [comment]
Just a heads up, I am experiencing this as well.  I have an ssh clone of this repository:
https://github.com/googleapis/google-api-nodejs-client

```
google-api-nodejs-client (master) $ git remote -v
origin	git@github.com:googleapis/google-api-nodejs-client.git (fetch)
origin	git@github.com:googleapis/google-api-nodejs-client.git (push)
```

I am using this code:
```js
const result = await git.checkout({ fs, dir: '.', ref: 'booper' });
```

And getting an error like this:
```
Promise { <pending> }
> (node:23490) UnhandledPromiseRejectionWarning: NotFoundError: Could not find origin/booper.
    at Function.resolve (/Users/beckwith/Code/google-api-nodejs-client/node_modules/isomorphic-git/index.cjs:1792:11)
    at async _checkout (/Users/beckwith/Code/google-api-nodejs-client/node_modules/isomorphic-git/index.cjs:5337:11)
    at async Object.checkout (/Users/beckwith/Code/google-api-nodejs-client/node_modules/isomorphic-git/index.cjs:5924:12)
(node:23490) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
```

**Comment by HansZimmer5000** [comment]
I had the same issue but solved it. 

Situation: Cloned Repo, Tried to checkout 'master' branch, Failure as mentioned in first message here.
Solution: Clone Repo, Fetch All (see below), Checkout 'master' branch, voila.

I fetched via:
```ts
await git.fetch({
  "path_to_directory",
  "remote_name_e.g._origin",
})
```

I assume the fetch is necessary since, in this repo, the 'master' branch is NOT the default branch.
