### ISSUE TITLE
Failure to expand reference master when it's there

### ISSUE THREAD

**Issue by TomasHubelbauer** [isomorphic-git/isomorphic-git#963]
I'm using the Node version and doing a pull of https://github.com/TomasHubelbauer/ef-core-sqlite to update it to the remote version. I think clone went successfully with no errors, however the pull fails with this error:

```
GitError [ExpandRefError]: Could not expand reference "master".
    at Function.expand (C:\Users\Tom\Desktop\github-backuper\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:2202:11)
    at async merge (C:\Users\Tom\Desktop\github-backuper\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:9633:12)
    at async Object.pull (C:\Users\Tom\Desktop\github-backuper\node_modules\isomorphic-git\dist\for-node\isomorphic-git\index.js:9959:5)
    at async backup (C:\Users\Tom\Desktop\github-backuper\index.js:41:11) {
  name: 'ExpandRefError',
  code: 'ExpandRefError',
  data: { ref: 'master' },
  message: 'Could not expand reference "master".',
  caller: 'git.pull'
}
```

The ref being passed to the expand method is `master` and I didn't look into the packed map stuff, but the contents of the `.git` repository don't look different from other, working repos.

**Comment by AxelTerizaki** [comment]
I confirm I have the same issue, but it's difficult to reproduce. It sometimes happens, sometimes not, but everytime it did I had issues with the .git directory inside the repo. Recloning usually fixed the issue.

**Comment by TomasHubelbauer** [comment]
I've also resorted to recloning the repository when this happens in it and it has no local changes.

**Comment by wmhilton** [comment]
Next time it happens, can you put the `.git` directory into a zip file and send it to me? This is one of those tricky cases where it's kinda hard to guess what's happening.
